/**
 * @file    Ecuc_Mcu_Cfg.h
 * @brief   AUTOSAR Mcu - MCU Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Mcu module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Mcu BSW module implementation.
 *
 * @module     Mcu
 * @moduleId   43
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.100Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_MCU_CFG_H
#define ECUC_MCU_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[module identification]==================================*/
/** @brief Mcu module identification (ECUC config data) */
#ifndef MCU_MODULE_ID
#define MCU_MODULE_ID            ((uint16)0x002B)
#endif /* MCU_MODULE_ID */
#ifndef MCU_VENDOR_ID
#define MCU_VENDOR_ID            ((uint16)0x1234)
#endif /* MCU_VENDOR_ID */

/*==================[parameter macros]======================================*/
#define MCU_MCUCLOCKSETTING    ((uint32)16000000U)
#define MCU_MCURAMSECTORS    ((uint16)4U)
#define MCU_MCUDEVERRORDETECT    STD_ON
#ifndef MCU_DEV_ERROR_DETECT
#define MCU_DEV_ERROR_DETECT    STD_ON
#endif /* MCU_DEV_ERROR_DETECT */
/** @brief Number of McuClockSettingConfig instances */
#define MCU_MCUCLOCKSETTINGCONFIG_COUNT    1U

/*==================[type definitions]======================================*/
/*==================[external data declarations]============================*/
#define MCU_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

#define MCU_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif /* ECUC_MCU_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page mcu_cfg_page Mcu Configuration
 * @brief This page documents the Mcu module configuration parameters.
 *
 * @section mcu_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Mcu AUTOSAR BSW module.
 *
 * @section mcu_cfg_usage Usage
 * Include this file in your Mcu module implementation to access
 * the configured parameters.
 *
 * @section mcu_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
