/**
 * @file    Ecuc_Mcu.c
 * @brief   AUTOSAR Mcu - MCU Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Mcu module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Mcu BSW module implementation.
 *
 * @module     Mcu
 * @moduleId   43
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.595Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Mcu_Cfg.h"

/*==================[module information]====================================*/
/**
 * @brief Mcu module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   43
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
static const Std_VersionInfoType Mcu_VersionInfo = {
    .vendorID = MCU_VENDOR_ID,
    .moduleID = MCU_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Mcu module initialization state */
static boolean Mcu_Initialized = FALSE;

/*==================[configuration data]==================================*/
#define MCU_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief McuClockSettingConfig instance 0 */
static const Mcu_McuClockSettingConfigType McuClockSettingConfig_Instance_0 = {
};

/** @brief McuClockSettingConfig instance array */
const Mcu_McuClockSettingConfigType McuClockSettingConfig_Instances[1] = {
    McuClockSettingConfig_Instance_0,
};

/** @brief Mcu configuration set structure */
const Mcu_ConfigSetType Mcu_ConfigSet = {
    .moduleId = MCU_MODULE_ID,
    .versionInfo = {4, 4, 0},
    .instanceCount = 1,
    .mcuClockSetting = ((uint32)16000000U),
    .mcuDevErrorDetect = STD_ON,
    .McuClockSettingConfig = McuClockSettingConfig_Instances,
};

/** @brief Mcu configuration type */
const Mcu_ConfigType Mcu_Config = {
    .configSet = &Mcu_ConfigSet,
};


#define MCU_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Mcu.c
 */
