/**
 * @file    Ecuc_Mcu_Cfg.h
 * @brief   AUTOSAR Mcu - MCU Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Mcu module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Mcu BSW module implementation.
 *
 * @module     Mcu
 * @moduleId   43
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.595Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_MCU_CFG_H
#define ECUC_MCU_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[AUTOSAR version information]============================*/
/**
 * @brief Mcu Software Version
 */
#define MCU_SW_MAJOR_VERSION          ((uint8)4U)
#define MCU_SW_MINOR_VERSION          ((uint8)4U)
#define MCU_SW_PATCH_VERSION          ((uint8)0U)

/**
 * @brief AUTOSAR Release Version
 */
#define MCU_AR_RELEASE_MAJOR_VERSION  ((uint8)4U)
#define MCU_AR_RELEASE_MINOR_VERSION  ((uint8)4U)
#define MCU_AR_RELEASE_REVISION_VERSION ((uint8)0U)

/**
 * @brief Module ID and Vendor ID
 */
#define MCU_MODULE_ID                 ((uint16)0x002B)
#define MCU_VENDOR_ID                 ((uint16)0x1234)

/**
 * @brief Development error detection switch
 */
#define MCU_DEV_ERROR_DETECT          STD_OFF

/*==================[vendor identification]==================================*/
/**
 * @brief YuleTech vendor information
 */
#define YULETECH_VENDOR_ID              ((uint16)0x1234)

/*==================[parameter macros]======================================*/
#define MCU_MCUCLOCKSETTING    ((uint32)16000000U)
#define MCU_MCUDEVERRORDETECT    STD_ON
/** @brief Number of McuClockSettingConfig instances */
#define MCU_MCUCLOCKSETTINGCONFIG_COUNT    1U

/*==================[type definitions]======================================*/
/** @brief Clock Setting container type */
typedef struct {
} Mcu_McuClockSettingConfigType;

/** @brief Mcu configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    uint32 mcuClockSetting;
    boolean mcuDevErrorDetect;
    const Mcu_McuClockSettingConfigType* McuClockSettingConfig;
} Mcu_ConfigSetType;

/** @brief Mcu configuration type */
typedef struct {
    const Mcu_ConfigSetType* configSet;
} Mcu_ConfigType;

/*==================[external data declarations]============================*/
#define MCU_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Mcu_ConfigSetType Mcu_ConfigSet;
/** @brief External configuration structure */
extern const Mcu_ConfigType Mcu_Config;

/** @brief McuClockSettingConfig container instances */
extern const Mcu_McuClockSettingConfigType McuClockSettingConfig_Instances[1];

#define MCU_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[function declarations]=================================*/
/**
 * @brief Initialize the Mcu module
 *
 * @param [in] ConfigPtr  Pointer to the Mcu configuration set
 *
 * @pre  The module shall be uninitialized
 *
 * @post The Mcu module is fully initialized and operational
 *
 * @return Std_ReturnType: E_OK if initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Mcu_Init(const Mcu_ConfigType* ConfigPtr);

/**
 * @brief De-initialize the Mcu module
 *
 * @pre  The Mcu module shall be initialized
 *
 * @post The Mcu module is de-initialized and no longer operational
 *
 * @return Std_ReturnType: E_OK if de-initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Mcu_DeInit(void);

/**
 * @brief Mcu main function - scheduled cyclic processing
 *
 * @pre  The Mcu module shall be initialized
 *
 * @post All pending Mcu processing is completed for this cycle
 *
 * @return void
 */
void Mcu_MainFunction(void);

/**
 * @brief Get the Mcu module version information
 *
 * @param [out] versioninfo  Pointer to the version information structure to be filled
 *
 * @pre  versioninfo shall not be NULL_PTR
 *
 * @post The version structure contains the Mcu module's vendor, module, and software version IDs
 *
 * @return void
 */
void Mcu_GetVersionInfo(Std_VersionInfoType* versioninfo);

/**
 * @brief Check if the Mcu module is initialized
 *
 * @return boolean: TRUE if the module is initialized, FALSE otherwise
 */
boolean Mcu_IsInitialized(void);

#endif /* ECUC_MCU_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page mcu_cfg_page Mcu Configuration
 * @brief This page documents the Mcu module configuration parameters.
 *
 * @section mcu_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Mcu AUTOSAR BSW module.
 *
 * @section mcu_cfg_usage Usage
 * Include this file in your Mcu module implementation to access
 * the configured parameters.
 *
 * @section mcu_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
