/**
 * @file    Ecuc_Mcu_Lcfg.c
 * @brief   AUTOSAR Mcu - MCU Driver Link-Time Configuration
 * @details This file contains the AUTOSAR 4.4 compliant Mcu module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Mcu BSW module implementation.
 *
 * @module     Mcu
 * @moduleId   43
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.596Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Mcu_Cfg.h"

/*==================[link-time configuration]===============================*/
/**
 * @brief Mcu Link-Time Configuration Data
 * @details This file contains configuration data that can be defined
 *          at link time. Link-Time configuration allows parameter changes
 *          at the final linking stage.
 */
/* Link-Time configurable data structures */
Mcu_ConfigSetType Mcu_Lcfg = {0};/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Mcu_Lcfg.c
 */
