/**
 * @file    Ecuc_Mcu.c
 * @brief   AUTOSAR Mcu - MCU Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Mcu module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Mcu BSW module implementation.
 *
 * @module     Mcu
 * @moduleId   43
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.100Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Mcu_Cfg.h"
#include "Mcu.h"

/*==================[module information]====================================*/
/**
 * @brief Mcu module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   43
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
__attribute__((unused)) static const Std_VersionInfoType Mcu_VersionInfo = {
    .vendorID = MCU_VENDOR_ID,
    .moduleID = MCU_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Mcu module initialization state */
__attribute__((unused)) static boolean Mcu_Initialized = FALSE;

#define MCU_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[yuleASR flat config - Mcu_Config]============*/
/**
 * @brief yuleASR flat configuration - Mcu_Config
 * @details
 * This section directly defines the Mcu_Config symbol expected by
 * yuleASR's Mcu.h driver header. The data is generated flat,
 * without the AUTOSAR ConfigSet nesting layer.
 *
 * The Mcu.h header is included at the top of this file.
 */

static const Mcu_ClockConfigType Mcu_ClockConfigs[1] = {
    {
        .PllBaseAddr = ((uint16)0U),
        .PllConfigs = NULL_PTR,
        .NumPllConfigs = 0U,
        .ClockSource = ((uint16)0U),
        .ArmDiv = ((uint16)0U),
        .AxiDiv = ((uint16)0U),
        .AhbDiv = ((uint16)0U),
    },
};

/** @brief Mcu ModeConfig (bridge) */
static const Mcu_ModeConfigType Mcu_ModeConfigs[1] = {
    { .Mode = ((uint16)0U) },
};

/** @brief yuleASR Mcu_Config instance */
const Mcu_ConfigType Mcu_Config = {
    .ClockSetting = ((uint32)16000000U),
    .ClockFrequency = ((uint32)1000000000U),
    .PllMultiplier = ((uint16)0U),
    .PllDivider = ((uint16)0U),
    .PllEnabled = STD_OFF,
    .RamSections = NULL_PTR,
    .NumRamSections = 0U,
    .ClockConfigs = Mcu_ClockConfigs,
    .NumClockConfigs = 1U,
    .ModeConfigs = Mcu_ModeConfigs,
    .NumModes = 1U,
};


#define MCU_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Mcu.c
 */
