/**
 * @file    Ecuc_Dio_Cfg.h
 * @brief   AUTOSAR Dio - DIO Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Dio module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Dio BSW module implementation.
 *
 * @module     Dio
 * @moduleId   41
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.597Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_DIO_CFG_H
#define ECUC_DIO_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[AUTOSAR version information]============================*/
/**
 * @brief Dio Software Version
 */
#define DIO_SW_MAJOR_VERSION          ((uint8)4U)
#define DIO_SW_MINOR_VERSION          ((uint8)4U)
#define DIO_SW_PATCH_VERSION          ((uint8)0U)

/**
 * @brief AUTOSAR Release Version
 */
#define DIO_AR_RELEASE_MAJOR_VERSION  ((uint8)4U)
#define DIO_AR_RELEASE_MINOR_VERSION  ((uint8)4U)
#define DIO_AR_RELEASE_REVISION_VERSION ((uint8)0U)

/**
 * @brief Module ID and Vendor ID
 */
#define DIO_MODULE_ID                 ((uint16)0x0029)
#define DIO_VENDOR_ID                 ((uint16)0x1234)

/**
 * @brief Development error detection switch
 */
#define DIO_DEV_ERROR_DETECT          STD_OFF

/*==================[vendor identification]==================================*/
/**
 * @brief YuleTech vendor information
 */
#define YULETECH_VENDOR_ID              ((uint16)0x1234)

/*==================[parameter macros]======================================*/
#define DIO_DIODEVERRORDETECT    STD_ON
#define DIO_DIONUMPORTS    ((uint16)8U)
/** @brief Number of DioPort instances */
#define DIO_DIOPORT_COUNT    1U

/*==================[type definitions]======================================*/
/** @brief DIO Port container type */
typedef struct {
} Dio_DioPortType;

/** @brief Dio configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean dioDevErrorDetect;
    uint32 dioNumPorts;
    const Dio_DioPortType* DioPort;
} Dio_ConfigSetType;

/** @brief Dio configuration type */
typedef struct {
    const Dio_ConfigSetType* configSet;
} Dio_ConfigType;

/*==================[external data declarations]============================*/
#define DIO_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Dio_ConfigSetType Dio_ConfigSet;
/** @brief External configuration structure */
extern const Dio_ConfigType Dio_Config;

/** @brief DioPort container instances */
extern const Dio_DioPortType DioPort_Instances[1];

#define DIO_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[function declarations]=================================*/
/**
 * @brief Initialize the Dio module
 *
 * @param [in] ConfigPtr  Pointer to the Dio configuration set
 *
 * @pre  The module shall be uninitialized
 *
 * @post The Dio module is fully initialized and operational
 *
 * @return Std_ReturnType: E_OK if initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Dio_Init(const Dio_ConfigType* ConfigPtr);

/**
 * @brief De-initialize the Dio module
 *
 * @pre  The Dio module shall be initialized
 *
 * @post The Dio module is de-initialized and no longer operational
 *
 * @return Std_ReturnType: E_OK if de-initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Dio_DeInit(void);

/**
 * @brief Dio main function - scheduled cyclic processing
 *
 * @pre  The Dio module shall be initialized
 *
 * @post All pending Dio processing is completed for this cycle
 *
 * @return void
 */
void Dio_MainFunction(void);

/**
 * @brief Get the Dio module version information
 *
 * @param [out] versioninfo  Pointer to the version information structure to be filled
 *
 * @pre  versioninfo shall not be NULL_PTR
 *
 * @post The version structure contains the Dio module's vendor, module, and software version IDs
 *
 * @return void
 */
void Dio_GetVersionInfo(Std_VersionInfoType* versioninfo);

/**
 * @brief Check if the Dio module is initialized
 *
 * @return boolean: TRUE if the module is initialized, FALSE otherwise
 */
boolean Dio_IsInitialized(void);

#endif /* ECUC_DIO_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page dio_cfg_page Dio Configuration
 * @brief This page documents the Dio module configuration parameters.
 *
 * @section dio_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Dio AUTOSAR BSW module.
 *
 * @section dio_cfg_usage Usage
 * Include this file in your Dio module implementation to access
 * the configured parameters.
 *
 * @section dio_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
