/**
 * @file    Ecuc_Dio_Cfg.h
 * @brief   AUTOSAR Dio - DIO Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Dio module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Dio BSW module implementation.
 *
 * @module     Dio
 * @moduleId   41
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.102Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_DIO_CFG_H
#define ECUC_DIO_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[module identification]==================================*/
/** @brief Dio module identification (ECUC config data) */
#ifndef DIO_MODULE_ID
#define DIO_MODULE_ID            ((uint16)0x0029)
#endif /* DIO_MODULE_ID */
#ifndef DIO_VENDOR_ID
#define DIO_VENDOR_ID            ((uint16)0x1234)
#endif /* DIO_VENDOR_ID */

/*==================[parameter macros]======================================*/
#define DIO_DIODEVERRORDETECT    STD_ON
#ifndef DIO_DEV_ERROR_DETECT
#define DIO_DEV_ERROR_DETECT    STD_ON
#endif /* DIO_DEV_ERROR_DETECT */
#define DIO_DIOVERSIONINFOAPI    STD_ON
#define DIO_DIOFLIPCHANNELAPI    STD_ON
#define DIO_DIONUMPORTS    ((uint16)8U)
/** @brief Number of DioPort instances */
#define DIO_DIOPORT_COUNT    2U
/** @brief Number of DioChannel instances */
#define DIO_DIOCHANNEL_COUNT    2U

/*==================[type definitions]======================================*/
/** @brief DIO Port container type */
typedef struct {
} Dio_DioPortType;

/** @brief DIO Channel container type */
typedef struct {
} Dio_DioChannelType;

/** @brief Dio configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean dioDevErrorDetect;
    boolean dioVersionInfoApi;
    boolean dioFlipChannelApi;
    uint32 dioNumPorts;
    const Dio_DioPortType* DioPort;
    const Dio_DioChannelType* DioChannel;
} Dio_ConfigSetType;

/*==================[external data declarations]============================*/
#define DIO_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Dio_ConfigSetType Dio_ConfigSet;

/** @brief DioPort container instances */
extern const Dio_DioPortType DioPort_Instances[2];
/** @brief DioChannel container instances */
extern const Dio_DioChannelType DioChannel_Instances[2];

#define DIO_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif /* ECUC_DIO_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page dio_cfg_page Dio Configuration
 * @brief This page documents the Dio module configuration parameters.
 *
 * @section dio_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Dio AUTOSAR BSW module.
 *
 * @section dio_cfg_usage Usage
 * Include this file in your Dio module implementation to access
 * the configured parameters.
 *
 * @section dio_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
