/**
 * @file    Ecuc_Dio.c
 * @brief   AUTOSAR Dio - DIO Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Dio module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Dio BSW module implementation.
 *
 * @module     Dio
 * @moduleId   41
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.597Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Dio_Cfg.h"

/*==================[module information]====================================*/
/**
 * @brief Dio module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   41
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
static const Std_VersionInfoType Dio_VersionInfo = {
    .vendorID = DIO_VENDOR_ID,
    .moduleID = DIO_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Dio module initialization state */
static boolean Dio_Initialized = FALSE;

/*==================[configuration data]==================================*/
#define DIO_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief DioPort instance 0 */
static const Dio_DioPortType DioPort_Instance_0 = {
};

/** @brief DioPort instance array */
const Dio_DioPortType DioPort_Instances[1] = {
    DioPort_Instance_0,
};

/** @brief Dio configuration set structure */
const Dio_ConfigSetType Dio_ConfigSet = {
    .moduleId = DIO_MODULE_ID,
    .versionInfo = {4, 4, 0},
    .instanceCount = 1,
    .dioDevErrorDetect = STD_ON,
    .dioNumPorts = ((uint16)8U),
    .DioPort = DioPort_Instances,
};

/** @brief Dio configuration type */
const Dio_ConfigType Dio_Config = {
    .configSet = &Dio_ConfigSet,
};


#define DIO_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Dio.c
 */
