/**
 * Built-in: MCAL Code Generator Plugin
 *
 * Generates AUTOSAR MCAL configuration code (C headers).
 * Supports: Can, Lin, Spi, Mcu, DIO, Pwm, Icu, Adc, Gpt, Wdg.
 */
import type { YulePlugin, PluginContext } from '@yuletech/plugin-sdk';
import type { ModuleConfig } from '../../types';
import { generatorRegistry } from '../../generator';

const MCAL_MODULES = [
  'Can', 'CanTrcv', 'Lin', 'LinTrcv', 'Spi', 'Mcu', 'Dio',
  'Pwm', 'Icu', 'Adc', 'Gpt', 'Wdg', 'Port',
];

const mcalGeneratorPlugin: YulePlugin = {
  id: 'yuletech-generator-mcal',
  name: 'MCAL Code Generator',
  version: '1.0.0',
  type: 'code-generator',
  description: '生成 AUTOSAR MCAL 配置 C 代码，支持 Can/Lin/Spi/Mcu 等 13 个 MCAL 模块',
  author: 'YuleTech',

  async activate(context: PluginContext): Promise<void> {
    context.registerCodeGenerator({
      name: 'McalConfigGenerator',
      description: 'MCAL configuration header generation',
      supportedModules: MCAL_MODULES,

      async generate(
        config: Record<string, unknown>,
        options: Record<string, unknown>
      ): Promise<{ files: { path: string; content: string }[] }> {
        const moduleName = (options.moduleName as string) ?? 'Unknown';
        const outputDir = (options.outputDir as string) ?? '.';
        const files: { path: string; content: string }[] = [];

        // Try using the GeneratorRegistry first
        const existingGenerator = generatorRegistry.findForModule(moduleName);
        if (existingGenerator) {
          // Delegate to the registered generator
          const moduleConfig: ModuleConfig = {
            module: moduleName,
            version: '4.4.0',
            parameters: config,
          };
          const result = await existingGenerator.generate(
            moduleConfig,
            { name: moduleName, version: '4.4.0', layer: 'mcal', parameters: [] },
            { outputDir, compiler: (options.compiler as string) ?? 'gcc' }
          );
          return {
            files: result.files.map(f => ({
              path: `${outputDir}/${f.path}`,
              content: f.content,
            })),
          };
        }

        // Fallback: generate basic configuration header
        const guard = `${moduleName.toUpperCase()}_CFG_H`;
        const timestamp = new Date().toISOString();
        const defines: string[] = [];

        for (const [key, value] of Object.entries(config)) {
          const defineName = `${moduleName.toUpperCase()}_${key.toUpperCase()}`;
          if (typeof value === 'boolean') {
            defines.push(`#define ${defineName}  ${value ? 'STD_ON' : 'STD_OFF'}`);
          } else if (typeof value === 'number') {
            const suffix = Number.isInteger(value) ? 'U' : '';
            defines.push(`#define ${defineName}  ${value}${suffix}`);
          } else {
            defines.push(`#define ${defineName}  ${value}`);
          }
        }

        const content = [
          `/* AUTOGENERATED - yuleASR MCAL Config Generator */`,
          `/* Module: ${moduleName} */`,
          `/* Timestamp: ${timestamp} */`,
          `/* AUTOSAR 4.4 */`,
          ``,
          `#ifndef ${guard}`,
          `#define ${guard}`,
          ``,
          `/*==================[includes]==============================================*/`,
          `#include "Std_Types.h"`,
          `#include "${moduleName}_GeneralTypes.h"`,
          ``,
          `/*==================[configuration macros]==================================*/`,
          ...defines,
          ``,
          `/*==================[type definitions]======================================*/`,
          `typedef struct {`,
          ...Object.keys(config).map(k => `    uint32 ${k};`),
          `} ${moduleName}_ConfigType;`,
          ``,
          `/*==================[external data]=========================================*/`,
          `extern const ${moduleName}_ConfigType ${moduleName}_Config;`,
          ``,
          `#endif /* ${guard} */`,
          `/*==================[end of file]===========================================*/`,
          ``,
        ].join('\n');

        files.push({
          path: `${outputDir}/${moduleName}_Cfg.h`,
          content,
        });

        return { files };
      },
    });

    context.logger.info(`MCAL Code Generator plugin activated (${MCAL_MODULES.length} modules)`);
  },

  async deactivate(): Promise<void> {
    // No cleanup needed
  },
};

export default mcalGeneratorPlugin;
