/**
 * @yuletech/core - Generator
 * 代码生成器接口定义
 */

import type { ModuleConfig, ModuleSchema } from '../types';

/**
 * 生成的文件
 */
export interface GeneratedFile {
  /** 文件路径 */
  path: string;
  /** 文件内容 */
  content: string;
  /** 语言 */
  language: 'c' | 'h' | 'xml' | 'json' | 'other';
}

/**
 * 生成结果
 */
export interface GenerationResult {
  /** 是否成功 */
  success: boolean;
  /** 生成的文件列表 */
  files: GeneratedFile[];
  /** 错误消息 */
  errors?: string[];
  /** 警告消息 */
  warnings?: string[];
}

/**
 * 生成器选项
 */
export interface GeneratorOptions {
  /** 输出目录 */
  outputDir: string;
  /** 目标平台 */
  targetPlatform?: string;
  /** 编译器 */
  compiler?: 'gcc' | 'iar' | 'ghs';
  /** 是否生成注释 */
  generateComments?: boolean;
  /** 是否格式化代码 */
  formatCode?: boolean;
}

/**
 * 代码生成器接口
 */
export interface CodeGenerator {
  /** 生成器名称 */
  name: string;
  /** 生成器版本 */
  version: string;
  /** 支持的模块列表 */
  supportedModules: string[];
  
  /**
   * 生成代码
   * @param config 模块配置
   * @param schema 模块 Schema
   * @param options 生成选项
   */
  generate(
    config: ModuleConfig,
    schema: ModuleSchema,
    options: GeneratorOptions
  ): Promise<GenerationResult>;
  
  /**
   * 检查是否支持该模块
   */
  supports(moduleName: string): boolean;
}

/**
 * 生成器注册表
 */
export class GeneratorRegistry {
  private generators = new Map<string, CodeGenerator>();

  register(generator: CodeGenerator): void {
    this.generators.set(generator.name, generator);
  }

  unregister(name: string): void {
    this.generators.delete(name);
  }

  get(name: string): CodeGenerator | undefined {
    return this.generators.get(name);
  }

  getAll(): CodeGenerator[] {
    return Array.from(this.generators.values());
  }

  findForModule(moduleName: string): CodeGenerator | undefined {
    return this.getAll().find(g => g.supports(moduleName));
  }
}

/**
 * 全局生成器注册表
 */
export const generatorRegistry = new GeneratorRegistry();

/**
 * 生成 C 头文件模板
 */
export function generateHeaderFile(
  moduleName: string,
  config: ModuleConfig,
  schema: ModuleSchema
): string {
  const guard = `${moduleName.toUpperCase()}_CFG_H`;
  const timestamp = new Date().toISOString();
  
  return `/* AUTOGENERATED FILE - DO NOT EDIT */
/* Generated by yuleASR Configurator */
/* Timestamp: ${timestamp} */
/* Module: ${schema.label || moduleName} */
/* Version: ${schema.version} */

#ifndef ${guard}
#define ${guard}

/*==================[includes]==============================================*/
#include "Std_Types.h"

/*==================[macros]================================================*/
${generateMacros(config, schema)}

/*==================[type definitions]======================================*/
${generateTypes(config, schema)}

/*==================[external data declarations]============================*/
${generateExternDeclarations(config, schema)}

#endif /* ${guard} */
/*==================[end of file]===========================================*/
`;
}

/**
 * 生成宏定义
 */
function generateMacros(config: ModuleConfig, schema: ModuleSchema): string {
  const macros: string[] = [];
  
  for (const [key, value] of Object.entries(config.parameters)) {
    const param = schema.parameters.find(p => p.name === key);
    if (!param) continue;
    
    const defineName = `${schema.name.toUpperCase()}_${key.toUpperCase()}`;
    
    if (typeof value === 'boolean') {
      macros.push(`#define ${defineName} ${value ? 'STD_ON' : 'STD_OFF'}`);
    } else if (typeof value === 'number') {
      macros.push(`#define ${defineName} ${value}U`);
    } else if (typeof value === 'string') {
      macros.push(`#define ${defineName} ${value}`);
    }
  }
  
  return macros.join('\n');
}

/**
 * 生成类型定义
 */
function generateTypes(_config: ModuleConfig, _schema: ModuleSchema): string {
  // 基础实现，可根据需要扩展
  return '';
}

/**
 * 生成外部声明
 */
function generateExternDeclarations(_config: ModuleConfig, schema: ModuleSchema): string {
  const externName = `${schema.name}_Config`;
  return `extern const ${schema.name}_ConfigType ${externName};`;
}
