/**
 * @file    Ecuc_Pwm_Cfg.h
 * @brief   AUTOSAR Pwm - PWM Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Pwm module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Pwm BSW module implementation.
 *
 * @module     Pwm
 * @moduleId   123
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.599Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_PWM_CFG_H
#define ECUC_PWM_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[AUTOSAR version information]============================*/
/**
 * @brief Pwm Software Version
 */
#define PWM_SW_MAJOR_VERSION          ((uint8)4U)
#define PWM_SW_MINOR_VERSION          ((uint8)4U)
#define PWM_SW_PATCH_VERSION          ((uint8)0U)

/**
 * @brief AUTOSAR Release Version
 */
#define PWM_AR_RELEASE_MAJOR_VERSION  ((uint8)4U)
#define PWM_AR_RELEASE_MINOR_VERSION  ((uint8)4U)
#define PWM_AR_RELEASE_REVISION_VERSION ((uint8)0U)

/**
 * @brief Module ID and Vendor ID
 */
#define PWM_MODULE_ID                 ((uint16)0x007B)
#define PWM_VENDOR_ID                 ((uint16)0x1234)

/**
 * @brief Development error detection switch
 */
#define PWM_DEV_ERROR_DETECT          STD_OFF

/*==================[vendor identification]==================================*/
/**
 * @brief YuleTech vendor information
 */
#define YULETECH_VENDOR_ID              ((uint16)0x1234)

/*==================[parameter macros]======================================*/
#define PWM_PWMDEVERRORDETECT    STD_ON
#define PWM_PWMNUMCHANNELS    ((uint16)8U)
/** @brief Number of PwmChannel instances */
#define PWM_PWMCHANNEL_COUNT    1U

/*==================[type definitions]======================================*/
/** @brief PWM Channel container type */
typedef struct {
} Pwm_PwmChannelType;

/** @brief Pwm configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean pwmDevErrorDetect;
    uint32 pwmNumChannels;
    const Pwm_PwmChannelType* PwmChannel;
} Pwm_ConfigSetType;

/** @brief Pwm configuration type */
typedef struct {
    const Pwm_ConfigSetType* configSet;
} Pwm_ConfigType;

/*==================[external data declarations]============================*/
#define PWM_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Pwm_ConfigSetType Pwm_ConfigSet;
/** @brief External configuration structure */
extern const Pwm_ConfigType Pwm_Config;

/** @brief PwmChannel container instances */
extern const Pwm_PwmChannelType PwmChannel_Instances[1];

#define PWM_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[function declarations]=================================*/
/**
 * @brief Initialize the Pwm module
 *
 * @param [in] ConfigPtr  Pointer to the Pwm configuration set
 *
 * @pre  The module shall be uninitialized
 *
 * @post The Pwm module is fully initialized and operational
 *
 * @return Std_ReturnType: E_OK if initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Pwm_Init(const Pwm_ConfigType* ConfigPtr);

/**
 * @brief De-initialize the Pwm module
 *
 * @pre  The Pwm module shall be initialized
 *
 * @post The Pwm module is de-initialized and no longer operational
 *
 * @return Std_ReturnType: E_OK if de-initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Pwm_DeInit(void);

/**
 * @brief Pwm main function - scheduled cyclic processing
 *
 * @pre  The Pwm module shall be initialized
 *
 * @post All pending Pwm processing is completed for this cycle
 *
 * @return void
 */
void Pwm_MainFunction(void);

/**
 * @brief Get the Pwm module version information
 *
 * @param [out] versioninfo  Pointer to the version information structure to be filled
 *
 * @pre  versioninfo shall not be NULL_PTR
 *
 * @post The version structure contains the Pwm module's vendor, module, and software version IDs
 *
 * @return void
 */
void Pwm_GetVersionInfo(Std_VersionInfoType* versioninfo);

/**
 * @brief Check if the Pwm module is initialized
 *
 * @return boolean: TRUE if the module is initialized, FALSE otherwise
 */
boolean Pwm_IsInitialized(void);

#endif /* ECUC_PWM_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page pwm_cfg_page Pwm Configuration
 * @brief This page documents the Pwm module configuration parameters.
 *
 * @section pwm_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Pwm AUTOSAR BSW module.
 *
 * @section pwm_cfg_usage Usage
 * Include this file in your Pwm module implementation to access
 * the configured parameters.
 *
 * @section pwm_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
