/**
 * @file    Ecuc_Pwm.c
 * @brief   AUTOSAR Pwm - PWM Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Pwm module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Pwm BSW module implementation.
 *
 * @module     Pwm
 * @moduleId   123
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.104Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Pwm_Cfg.h"

/*==================[module information]====================================*/
/**
 * @brief Pwm module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   123
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
__attribute__((unused)) static const Std_VersionInfoType Pwm_VersionInfo = {
    .vendorID = PWM_VENDOR_ID,
    .moduleID = PWM_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Pwm module initialization state */
__attribute__((unused)) static boolean Pwm_Initialized = FALSE;

/*==================[configuration data]==================================*/
#define PWM_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief PwmChannel instance 0 */
static const Pwm_PwmChannelType PwmChannel_Instance_0 = {
};

/** @brief PwmChannel instance 1 */
static const Pwm_PwmChannelType PwmChannel_Instance_1 = {
};

/** @brief PwmChannel instance array */
const Pwm_PwmChannelType PwmChannel_Instances[2] = {
    PwmChannel_Instance_0,
    PwmChannel_Instance_1,
};

/** @brief Pwm configuration set structure */
const Pwm_ConfigSetType Pwm_ConfigSet = {
    .moduleId = PWM_MODULE_ID,
    .versionInfo = {4, 4, 0},
    .instanceCount = 2,
    .pwmDevErrorDetect = STD_ON,
    .pwmNumChannels = ((uint16)8U),
    .PwmChannel = PwmChannel_Instances,
};


#define PWM_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Pwm.c
 */
