/**
 * @file    Ecuc_Pwm_Cfg.h
 * @brief   AUTOSAR Pwm - PWM Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Pwm module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Pwm BSW module implementation.
 *
 * @module     Pwm
 * @moduleId   123
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.104Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_PWM_CFG_H
#define ECUC_PWM_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[module identification]==================================*/
/** @brief Pwm module identification (ECUC config data) */
#ifndef PWM_MODULE_ID
#define PWM_MODULE_ID            ((uint16)0x007B)
#endif /* PWM_MODULE_ID */
#ifndef PWM_VENDOR_ID
#define PWM_VENDOR_ID            ((uint16)0x1234)
#endif /* PWM_VENDOR_ID */

/*==================[parameter macros]======================================*/
#define PWM_PWMDEVERRORDETECT    STD_ON
#ifndef PWM_DEV_ERROR_DETECT
#define PWM_DEV_ERROR_DETECT    STD_ON
#endif /* PWM_DEV_ERROR_DETECT */
#define PWM_PWMNUMCHANNELS    ((uint16)8U)
/** @brief Number of PwmChannel instances */
#define PWM_PWMCHANNEL_COUNT    2U

/*==================[type definitions]======================================*/
/** @brief PWM Channel container type */
typedef struct {
} Pwm_PwmChannelType;

/** @brief Pwm configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean pwmDevErrorDetect;
    uint32 pwmNumChannels;
    const Pwm_PwmChannelType* PwmChannel;
} Pwm_ConfigSetType;

/*==================[external data declarations]============================*/
#define PWM_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Pwm_ConfigSetType Pwm_ConfigSet;

/** @brief PwmChannel container instances */
extern const Pwm_PwmChannelType PwmChannel_Instances[2];

#define PWM_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif /* ECUC_PWM_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page pwm_cfg_page Pwm Configuration
 * @brief This page documents the Pwm module configuration parameters.
 *
 * @section pwm_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Pwm AUTOSAR BSW module.
 *
 * @section pwm_cfg_usage Usage
 * Include this file in your Pwm module implementation to access
 * the configured parameters.
 *
 * @section pwm_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
