/**
 * @file    Ecuc_Adc_Cfg.h
 * @brief   AUTOSAR Adc - ADC Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Adc module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Adc BSW module implementation.
 *
 * @module     Adc
 * @moduleId   44
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.598Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_ADC_CFG_H
#define ECUC_ADC_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[AUTOSAR version information]============================*/
/**
 * @brief Adc Software Version
 */
#define ADC_SW_MAJOR_VERSION          ((uint8)4U)
#define ADC_SW_MINOR_VERSION          ((uint8)4U)
#define ADC_SW_PATCH_VERSION          ((uint8)0U)

/**
 * @brief AUTOSAR Release Version
 */
#define ADC_AR_RELEASE_MAJOR_VERSION  ((uint8)4U)
#define ADC_AR_RELEASE_MINOR_VERSION  ((uint8)4U)
#define ADC_AR_RELEASE_REVISION_VERSION ((uint8)0U)

/**
 * @brief Module ID and Vendor ID
 */
#define ADC_MODULE_ID                 ((uint16)0x002C)
#define ADC_VENDOR_ID                 ((uint16)0x1234)

/**
 * @brief Development error detection switch
 */
#define ADC_DEV_ERROR_DETECT          STD_OFF

/*==================[vendor identification]==================================*/
/**
 * @brief YuleTech vendor information
 */
#define YULETECH_VENDOR_ID              ((uint16)0x1234)

/*==================[parameter macros]======================================*/
#define ADC_ADCDEVERRORDETECT    STD_ON
#define ADC_ADCNUMHWUNITS    ((uint16)2U)
#define ADC_ADCNUMGROUPS    ((uint16)8U)
#define ADC_ADCNUMCHANNELS    ((uint16)16U)
/** @brief Number of AdcHwUnit instances */
#define ADC_ADCHWUNIT_COUNT    1U
/** @brief Number of AdcGroup instances */
#define ADC_ADCGROUP_COUNT    1U

/*==================[type definitions]======================================*/
/** @brief ADC HW Unit container type */
typedef struct {
} Adc_AdcHwUnitType;

/** @brief ADC Group container type */
typedef struct {
} Adc_AdcGroupType;

/** @brief Adc configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean adcDevErrorDetect;
    uint32 adcNumHwUnits;
    uint32 adcNumGroups;
    uint32 adcNumChannels;
    const Adc_AdcHwUnitType* AdcHwUnit;
    const Adc_AdcGroupType* AdcGroup;
} Adc_ConfigSetType;

/** @brief Adc configuration type */
typedef struct {
    const Adc_ConfigSetType* configSet;
} Adc_ConfigType;

/*==================[external data declarations]============================*/
#define ADC_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Adc_ConfigSetType Adc_ConfigSet;
/** @brief External configuration structure */
extern const Adc_ConfigType Adc_Config;

/** @brief AdcHwUnit container instances */
extern const Adc_AdcHwUnitType AdcHwUnit_Instances[1];
/** @brief AdcGroup container instances */
extern const Adc_AdcGroupType AdcGroup_Instances[1];

#define ADC_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[function declarations]=================================*/
/**
 * @brief Initialize the Adc module
 *
 * @param [in] ConfigPtr  Pointer to the Adc configuration set
 *
 * @pre  The module shall be uninitialized
 *
 * @post The Adc module is fully initialized and operational
 *
 * @return Std_ReturnType: E_OK if initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Adc_Init(const Adc_ConfigType* ConfigPtr);

/**
 * @brief De-initialize the Adc module
 *
 * @pre  The Adc module shall be initialized
 *
 * @post The Adc module is de-initialized and no longer operational
 *
 * @return Std_ReturnType: E_OK if de-initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Adc_DeInit(void);

/**
 * @brief Adc main function - scheduled cyclic processing
 *
 * @pre  The Adc module shall be initialized
 *
 * @post All pending Adc processing is completed for this cycle
 *
 * @return void
 */
void Adc_MainFunction(void);

/**
 * @brief Get the Adc module version information
 *
 * @param [out] versioninfo  Pointer to the version information structure to be filled
 *
 * @pre  versioninfo shall not be NULL_PTR
 *
 * @post The version structure contains the Adc module's vendor, module, and software version IDs
 *
 * @return void
 */
void Adc_GetVersionInfo(Std_VersionInfoType* versioninfo);

/**
 * @brief Check if the Adc module is initialized
 *
 * @return boolean: TRUE if the module is initialized, FALSE otherwise
 */
boolean Adc_IsInitialized(void);

#endif /* ECUC_ADC_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page adc_cfg_page Adc Configuration
 * @brief This page documents the Adc module configuration parameters.
 *
 * @section adc_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Adc AUTOSAR BSW module.
 *
 * @section adc_cfg_usage Usage
 * Include this file in your Adc module implementation to access
 * the configured parameters.
 *
 * @section adc_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
