/**
 * @file    Ecuc_Adc_Cfg.h
 * @brief   AUTOSAR Adc - ADC Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Adc module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Adc BSW module implementation.
 *
 * @module     Adc
 * @moduleId   44
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.103Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_ADC_CFG_H
#define ECUC_ADC_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[module identification]==================================*/
/** @brief Adc module identification (ECUC config data) */
#ifndef ADC_MODULE_ID
#define ADC_MODULE_ID            ((uint16)0x002C)
#endif /* ADC_MODULE_ID */
#ifndef ADC_VENDOR_ID
#define ADC_VENDOR_ID            ((uint16)0x1234)
#endif /* ADC_VENDOR_ID */

/*==================[parameter macros]======================================*/
#define ADC_ADCDEVERRORDETECT    STD_ON
#ifndef ADC_DEV_ERROR_DETECT
#define ADC_DEV_ERROR_DETECT    STD_ON
#endif /* ADC_DEV_ERROR_DETECT */
#define ADC_ADCNUMHWUNITS    ((uint16)2U)
#define ADC_ADCNUMGROUPS    ((uint16)8U)
#define ADC_ADCNUMCHANNELS    ((uint16)16U)
/** @brief Number of AdcHwUnit instances */
#define ADC_ADCHWUNIT_COUNT    2U
/** @brief Number of AdcGroup instances */
#define ADC_ADCGROUP_COUNT    1U
/** @brief Number of AdcChannel instances */
#define ADC_ADCCHANNEL_COUNT    2U

/*==================[type definitions]======================================*/
/** @brief ADC HW Unit container type */
typedef struct {
} Adc_AdcHwUnitType;

/** @brief ADC Group container type */
typedef struct {
} Adc_AdcGroupType;

/** @brief ADC Channel container type */
typedef struct {
} Adc_AdcChannelType;

/** @brief Adc configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean adcDevErrorDetect;
    uint32 adcNumHwUnits;
    uint32 adcNumGroups;
    uint32 adcNumChannels;
    const Adc_AdcHwUnitType* AdcHwUnit;
    const Adc_AdcGroupType* AdcGroup;
    const Adc_AdcChannelType* AdcChannel;
} Adc_ConfigSetType;

/*==================[external data declarations]============================*/
#define ADC_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Adc_ConfigSetType Adc_ConfigSet;

/** @brief AdcHwUnit container instances */
extern const Adc_AdcHwUnitType AdcHwUnit_Instances[2];
/** @brief AdcGroup container instances */
extern const Adc_AdcGroupType AdcGroup_Instances[1];
/** @brief AdcChannel container instances */
extern const Adc_AdcChannelType AdcChannel_Instances[2];

#define ADC_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif /* ECUC_ADC_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page adc_cfg_page Adc Configuration
 * @brief This page documents the Adc module configuration parameters.
 *
 * @section adc_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Adc AUTOSAR BSW module.
 *
 * @section adc_cfg_usage Usage
 * Include this file in your Adc module implementation to access
 * the configured parameters.
 *
 * @section adc_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
