/**
 * @file    Ecuc_Adc.c
 * @brief   AUTOSAR Adc - ADC Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Adc module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Adc BSW module implementation.
 *
 * @module     Adc
 * @moduleId   44
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.598Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Adc_Cfg.h"

/*==================[module information]====================================*/
/**
 * @brief Adc module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   44
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
static const Std_VersionInfoType Adc_VersionInfo = {
    .vendorID = ADC_VENDOR_ID,
    .moduleID = ADC_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Adc module initialization state */
static boolean Adc_Initialized = FALSE;

/*==================[configuration data]==================================*/
#define ADC_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief AdcHwUnit instance 0 */
static const Adc_AdcHwUnitType AdcHwUnit_Instance_0 = {
};

/** @brief AdcHwUnit instance array */
const Adc_AdcHwUnitType AdcHwUnit_Instances[1] = {
    AdcHwUnit_Instance_0,
};

/** @brief AdcGroup instance 0 */
static const Adc_AdcGroupType AdcGroup_Instance_0 = {
};

/** @brief AdcGroup instance array */
const Adc_AdcGroupType AdcGroup_Instances[1] = {
    AdcGroup_Instance_0,
};

/** @brief Adc configuration set structure */
const Adc_ConfigSetType Adc_ConfigSet = {
    .moduleId = ADC_MODULE_ID,
    .versionInfo = {4, 4, 0},
    .instanceCount = 1,
    .adcDevErrorDetect = STD_ON,
    .adcNumHwUnits = ((uint16)2U),
    .adcNumGroups = ((uint16)8U),
    .adcNumChannels = ((uint16)16U),
    .AdcHwUnit = AdcHwUnit_Instances,
    .AdcGroup = AdcGroup_Instances,
};

/** @brief Adc configuration type */
const Adc_ConfigType Adc_Config = {
    .configSet = &Adc_ConfigSet,
};


#define ADC_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Adc.c
 */
