/**
 * @file    Ecuc_Can_Cfg.h
 * @brief   AUTOSAR Can - CAN Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Can module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Can BSW module implementation.
 *
 * @module     Can
 * @moduleId   80
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.589Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_CAN_CFG_H
#define ECUC_CAN_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[AUTOSAR version information]============================*/
/**
 * @brief Can Software Version
 */
#define CAN_SW_MAJOR_VERSION          ((uint8)4U)
#define CAN_SW_MINOR_VERSION          ((uint8)4U)
#define CAN_SW_PATCH_VERSION          ((uint8)0U)

/**
 * @brief AUTOSAR Release Version
 */
#define CAN_AR_RELEASE_MAJOR_VERSION  ((uint8)4U)
#define CAN_AR_RELEASE_MINOR_VERSION  ((uint8)4U)
#define CAN_AR_RELEASE_REVISION_VERSION ((uint8)0U)

/**
 * @brief Module ID and Vendor ID
 */
#define CAN_MODULE_ID                 ((uint16)0x0050)
#define CAN_VENDOR_ID                 ((uint16)0x1234)

/**
 * @brief Development error detection switch
 */
#define CAN_DEV_ERROR_DETECT          STD_OFF

/*==================[vendor identification]==================================*/
/**
 * @brief YuleTech vendor information
 */
#define YULETECH_VENDOR_ID              ((uint16)0x1234)

/*==================[parameter macros]======================================*/
#define CAN_CANDEVERRORDETECT    STD_ON
#define CAN_CANNUMCONTROLLERS    ((uint16)2U)
/** @brief Number of CanController instances */
#define CAN_CANCONTROLLER_COUNT    1U

/*==================[type definitions]======================================*/
/** @brief CAN Controller container type */
typedef struct {
} Can_CanControllerType;

/** @brief Can configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean canDevErrorDetect;
    uint32 canNumControllers;
    const Can_CanControllerType* CanController;
} Can_ConfigSetType;

/** @brief Can configuration type */
typedef struct {
    const Can_ConfigSetType* configSet;
} Can_ConfigType;

/*==================[external data declarations]============================*/
#define CAN_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Can_ConfigSetType Can_ConfigSet;
/** @brief External configuration structure */
extern const Can_ConfigType Can_Config;

/** @brief CanController container instances */
extern const Can_CanControllerType CanController_Instances[1];

#define CAN_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[function declarations]=================================*/
/**
 * @brief Initialize the Can module
 *
 * @param [in] ConfigPtr  Pointer to the Can configuration set
 *
 * @pre  The module shall be uninitialized
 *
 * @post The Can module is fully initialized and operational
 *
 * @return Std_ReturnType: E_OK if initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Can_Init(const Can_ConfigType* ConfigPtr);

/**
 * @brief De-initialize the Can module
 *
 * @pre  The Can module shall be initialized
 *
 * @post The Can module is de-initialized and no longer operational
 *
 * @return Std_ReturnType: E_OK if de-initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Can_DeInit(void);

/**
 * @brief Can main function - scheduled cyclic processing
 *
 * @pre  The Can module shall be initialized
 *
 * @post All pending Can processing is completed for this cycle
 *
 * @return void
 */
void Can_MainFunction(void);

/**
 * @brief Get the Can module version information
 *
 * @param [out] versioninfo  Pointer to the version information structure to be filled
 *
 * @pre  versioninfo shall not be NULL_PTR
 *
 * @post The version structure contains the Can module's vendor, module, and software version IDs
 *
 * @return void
 */
void Can_GetVersionInfo(Std_VersionInfoType* versioninfo);

/**
 * @brief Check if the Can module is initialized
 *
 * @return boolean: TRUE if the module is initialized, FALSE otherwise
 */
boolean Can_IsInitialized(void);

#endif /* ECUC_CAN_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page can_cfg_page Can Configuration
 * @brief This page documents the Can module configuration parameters.
 *
 * @section can_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Can AUTOSAR BSW module.
 *
 * @section can_cfg_usage Usage
 * Include this file in your Can module implementation to access
 * the configured parameters.
 *
 * @section can_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
