/**
 * @file    Ecuc_Can.c
 * @brief   AUTOSAR Can - CAN Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Can module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Can BSW module implementation.
 *
 * @module     Can
 * @moduleId   80
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.098Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Can_Cfg.h"
#include "Can.h"

/*==================[module information]====================================*/
/**
 * @brief Can module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   80
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
__attribute__((unused)) static const Std_VersionInfoType Can_VersionInfo = {
    .vendorID = CAN_VENDOR_ID,
    .moduleID = CAN_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Can module initialization state */
__attribute__((unused)) static boolean Can_Initialized = FALSE;

#define CAN_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[yuleASR flat config - Can_Config]============*/
/**
 * @brief yuleASR flat configuration - Can_Config
 * @details
 * This section directly defines the Can_Config symbol expected by
 * yuleASR's Can.h driver header. The data is generated flat,
 * without the AUTOSAR ConfigSet nesting layer.
 *
 * The Can.h header is included at the top of this file.
 */

/** @brief Can Controller array */
static const Can_ControllerConfigType Can_Controllers[2] = {
    {
        .ControllerId = ((uint16)0U),
        .BaseAddress = ((uint16)0U),
        .BaudrateConfigs = NULL_PTR,
        .NumBaudrateConfigs = 0U,
        .HardwareObjects = NULL_PTR,
        .NumHardwareObjects = 0U,
        .RxProcessing = ((uint16)0U),
        .TxProcessing = ((uint16)0U),
        .BusOffProcessing = STD_OFF,
        .WakeupProcessing = STD_OFF,
        .WakeupSupport = STD_OFF,
        .DefaultBaudrateIndex = ((uint16)0U),
    },
    {
        .ControllerId = ((uint16)1U),
        .BaseAddress = ((uint16)0U),
        .BaudrateConfigs = NULL_PTR,
        .NumBaudrateConfigs = 0U,
        .HardwareObjects = NULL_PTR,
        .NumHardwareObjects = 0U,
        .RxProcessing = ((uint16)0U),
        .TxProcessing = ((uint16)0U),
        .BusOffProcessing = STD_OFF,
        .WakeupProcessing = STD_OFF,
        .WakeupSupport = STD_OFF,
        .DefaultBaudrateIndex = ((uint16)0U),
    },
};

/** @brief yuleASR Can_Config instance (bridge from ECUC ConfigSet) */
const Can_ConfigType Can_Config = {
    .Controllers = Can_Controllers,
    .NumControllers = 2U,
    .DevErrorDetect = (boolean)CAN_DEV_ERROR_DETECT,
    .VersionInfoApi = STD_ON,
};


#define CAN_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Can.c
 */
