/**
 * @file    Ecuc_Can.c
 * @brief   AUTOSAR Can - CAN Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Can module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Can BSW module implementation.
 *
 * @module     Can
 * @moduleId   80
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.591Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Can_Cfg.h"

/*==================[module information]====================================*/
/**
 * @brief Can module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   80
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
static const Std_VersionInfoType Can_VersionInfo = {
    .vendorID = CAN_VENDOR_ID,
    .moduleID = CAN_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Can module initialization state */
static boolean Can_Initialized = FALSE;

/*==================[configuration data]==================================*/
#define CAN_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief CanController instance 0 */
static const Can_CanControllerType CanController_Instance_0 = {
};

/** @brief CanController instance array */
const Can_CanControllerType CanController_Instances[1] = {
    CanController_Instance_0,
};

/** @brief Can configuration set structure */
const Can_ConfigSetType Can_ConfigSet = {
    .moduleId = CAN_MODULE_ID,
    .versionInfo = {4, 4, 0},
    .instanceCount = 1,
    .canDevErrorDetect = STD_ON,
    .canNumControllers = ((uint16)2U),
    .CanController = CanController_Instances,
};

/** @brief Can configuration type */
const Can_ConfigType Can_Config = {
    .configSet = &Can_ConfigSet,
};


#define CAN_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Can.c
 */
