/**
 * @file    Ecuc_Can.c
 * @brief   AUTOSAR Can - CAN Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Can module
 *          configuration data structures.
 *          Flat output: no AUTOSAR ConfigSet nesting, directly fills
 *          Can_ConfigType as defined in yuleASR's Can.h.
 *
 * @module     Can
 * @moduleId   80
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-29T18:49:00.000Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Can_Cfg.h"
#include "Can.h"

/*==================[module information]====================================*/
/**
 * @brief Can module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   80
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
static const Std_VersionInfoType Can_VersionInfo = {
    .vendorID = CAN_VENDOR_ID,
    .moduleID = CAN_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Can module initialization state */
static boolean Can_Initialized = FALSE;

/*==================[yuleASR flat config - Can_Config]======================*/
/**
 * @brief yuleASR flat configuration - Can_Config
 * @details
 * This section directly defines the Can_Config symbol expected by
 * yuleASR's Can.h driver header. The data is generated flat,
 * without the AUTOSAR ConfigSet nesting layer.
 *
 * The Can.h header is included at the top of this file.
 */

#define CAN_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/** @brief Controller 0 Config */
static const Can_ControllerConfigType Controller_0_Config = {
    .ControllerId = 0U,
    .BaseAddress = 0U,
    .BaudrateConfigs = NULL_PTR,
    .NumBaudrateConfigs = 0U,
    .HardwareObjects = NULL_PTR,
    .NumHardwareObjects = 0U,
    .RxProcessing = 0U,
    .TxProcessing = 0U,
    .BusOffProcessing = FALSE,
    .WakeupProcessing = FALSE,
    .WakeupSupport = FALSE,
    .DefaultBaudrateIndex = 0U,
};

/** @brief Controller 1 Config */
static const Can_ControllerConfigType Controller_1_Config = {
    .ControllerId = 1U,
    .BaseAddress = 0U,
    .BaudrateConfigs = NULL_PTR,
    .NumBaudrateConfigs = 0U,
    .HardwareObjects = NULL_PTR,
    .NumHardwareObjects = 0U,
    .RxProcessing = 0U,
    .TxProcessing = 0U,
    .BusOffProcessing = FALSE,
    .WakeupProcessing = FALSE,
    .WakeupSupport = FALSE,
    .DefaultBaudrateIndex = 0U,
};

/** @brief Can Controller array */
static const Can_ControllerConfigType Can_Controllers[2] = {
    Controller_0_Config,
    Controller_1_Config,
};

/** @brief yuleASR Can_Config instance (flat bridge) */
const Can_ConfigType Can_Config = {
    .Controllers = Can_Controllers,
    .NumControllers = 2U,
    .DevErrorDetect = (boolean)CAN_DEV_ERROR_DETECT,
    .VersionInfoApi = STD_ON,
};

#define CAN_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Can.c
 */
