/**
 * @file    Ecuc_Can_Cfg.h
 * @brief   AUTOSAR Can - CAN Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Can module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Can BSW module implementation.
 *
 * @module     Can
 * @moduleId   80
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.097Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_CAN_CFG_H
#define ECUC_CAN_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[module identification]==================================*/
/** @brief Can module identification (ECUC config data) */
#ifndef CAN_MODULE_ID
#define CAN_MODULE_ID            ((uint16)0x0050)
#endif /* CAN_MODULE_ID */
#ifndef CAN_VENDOR_ID
#define CAN_VENDOR_ID            ((uint16)0x1234)
#endif /* CAN_VENDOR_ID */

/*==================[parameter macros]======================================*/
#define CAN_CANDEVERRORDETECT    STD_ON
#ifndef CAN_DEV_ERROR_DETECT
#define CAN_DEV_ERROR_DETECT    STD_ON
#endif /* CAN_DEV_ERROR_DETECT */
#define CAN_CANVERSIONINFOAPI    STD_ON
#define CAN_CANNUMCONTROLLERS    ((uint16)2U)
#define CAN_CANNUMHOH    ((uint16)8U)
/** @brief Number of CanController instances */
#define CAN_CANCONTROLLER_COUNT    2U
/** @brief Number of CanHardwareObject instances */
#define CAN_CANHARDWAREOBJECT_COUNT    2U

/*==================[type definitions]======================================*/
/*==================[external data declarations]============================*/
#define CAN_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

#define CAN_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif /* ECUC_CAN_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page can_cfg_page Can Configuration
 * @brief This page documents the Can module configuration parameters.
 *
 * @section can_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Can AUTOSAR BSW module.
 *
 * @section can_cfg_usage Usage
 * Include this file in your Can module implementation to access
 * the configured parameters.
 *
 * @section can_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
