/**
 * @file    Ecuc_Gpt.c
 * @brief   AUTOSAR Gpt - GPT Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Gpt module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Gpt BSW module implementation.
 *
 * @module     Gpt
 * @moduleId   121
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.599Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Gpt_Cfg.h"

/*==================[module information]====================================*/
/**
 * @brief Gpt module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   121
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
static const Std_VersionInfoType Gpt_VersionInfo = {
    .vendorID = GPT_VENDOR_ID,
    .moduleID = GPT_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Gpt module initialization state */
static boolean Gpt_Initialized = FALSE;

/*==================[configuration data]==================================*/
#define GPT_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief GptChannel instance 0 */
static const Gpt_GptChannelType GptChannel_Instance_0 = {
};

/** @brief GptChannel instance array */
const Gpt_GptChannelType GptChannel_Instances[1] = {
    GptChannel_Instance_0,
};

/** @brief Gpt configuration set structure */
const Gpt_ConfigSetType Gpt_ConfigSet = {
    .moduleId = GPT_MODULE_ID,
    .versionInfo = {4, 4, 0},
    .instanceCount = 1,
    .gptDevErrorDetect = STD_ON,
    .gptNumChannels = ((uint16)8U),
    .GptChannel = GptChannel_Instances,
};

/** @brief Gpt configuration type */
const Gpt_ConfigType Gpt_Config = {
    .configSet = &Gpt_ConfigSet,
};


#define GPT_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Gpt.c
 */
