/**
 * @file    Ecuc_Gpt_Cfg.h
 * @brief   AUTOSAR Gpt - GPT Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Gpt module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Gpt BSW module implementation.
 *
 * @module     Gpt
 * @moduleId   121
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.104Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_GPT_CFG_H
#define ECUC_GPT_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[module identification]==================================*/
/** @brief Gpt module identification (ECUC config data) */
#ifndef GPT_MODULE_ID
#define GPT_MODULE_ID            ((uint16)0x0079)
#endif /* GPT_MODULE_ID */
#ifndef GPT_VENDOR_ID
#define GPT_VENDOR_ID            ((uint16)0x1234)
#endif /* GPT_VENDOR_ID */

/*==================[parameter macros]======================================*/
#define GPT_GPTDEVERRORDETECT    STD_ON
#ifndef GPT_DEV_ERROR_DETECT
#define GPT_DEV_ERROR_DETECT    STD_ON
#endif /* GPT_DEV_ERROR_DETECT */
#define GPT_GPTNUMCHANNELS    ((uint16)8U)
/** @brief Number of GptChannel instances */
#define GPT_GPTCHANNEL_COUNT    2U

/*==================[type definitions]======================================*/
/** @brief GPT Channel container type */
typedef struct {
} Gpt_GptChannelType;

/** @brief Gpt configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean gptDevErrorDetect;
    uint32 gptNumChannels;
    const Gpt_GptChannelType* GptChannel;
} Gpt_ConfigSetType;

/*==================[external data declarations]============================*/
#define GPT_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Gpt_ConfigSetType Gpt_ConfigSet;

/** @brief GptChannel container instances */
extern const Gpt_GptChannelType GptChannel_Instances[2];

#define GPT_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif /* ECUC_GPT_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page gpt_cfg_page Gpt Configuration
 * @brief This page documents the Gpt module configuration parameters.
 *
 * @section gpt_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Gpt AUTOSAR BSW module.
 *
 * @section gpt_cfg_usage Usage
 * Include this file in your Gpt module implementation to access
 * the configured parameters.
 *
 * @section gpt_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
