/**
 * @file    Ecuc_Gpt_Cfg.h
 * @brief   AUTOSAR Gpt - GPT Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Gpt module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Gpt BSW module implementation.
 *
 * @module     Gpt
 * @moduleId   121
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.599Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_GPT_CFG_H
#define ECUC_GPT_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[AUTOSAR version information]============================*/
/**
 * @brief Gpt Software Version
 */
#define GPT_SW_MAJOR_VERSION          ((uint8)4U)
#define GPT_SW_MINOR_VERSION          ((uint8)4U)
#define GPT_SW_PATCH_VERSION          ((uint8)0U)

/**
 * @brief AUTOSAR Release Version
 */
#define GPT_AR_RELEASE_MAJOR_VERSION  ((uint8)4U)
#define GPT_AR_RELEASE_MINOR_VERSION  ((uint8)4U)
#define GPT_AR_RELEASE_REVISION_VERSION ((uint8)0U)

/**
 * @brief Module ID and Vendor ID
 */
#define GPT_MODULE_ID                 ((uint16)0x0079)
#define GPT_VENDOR_ID                 ((uint16)0x1234)

/**
 * @brief Development error detection switch
 */
#define GPT_DEV_ERROR_DETECT          STD_OFF

/*==================[vendor identification]==================================*/
/**
 * @brief YuleTech vendor information
 */
#define YULETECH_VENDOR_ID              ((uint16)0x1234)

/*==================[parameter macros]======================================*/
#define GPT_GPTDEVERRORDETECT    STD_ON
#define GPT_GPTNUMCHANNELS    ((uint16)8U)
/** @brief Number of GptChannel instances */
#define GPT_GPTCHANNEL_COUNT    1U

/*==================[type definitions]======================================*/
/** @brief GPT Channel container type */
typedef struct {
} Gpt_GptChannelType;

/** @brief Gpt configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean gptDevErrorDetect;
    uint32 gptNumChannels;
    const Gpt_GptChannelType* GptChannel;
} Gpt_ConfigSetType;

/** @brief Gpt configuration type */
typedef struct {
    const Gpt_ConfigSetType* configSet;
} Gpt_ConfigType;

/*==================[external data declarations]============================*/
#define GPT_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Gpt_ConfigSetType Gpt_ConfigSet;
/** @brief External configuration structure */
extern const Gpt_ConfigType Gpt_Config;

/** @brief GptChannel container instances */
extern const Gpt_GptChannelType GptChannel_Instances[1];

#define GPT_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[function declarations]=================================*/
/**
 * @brief Initialize the Gpt module
 *
 * @param [in] ConfigPtr  Pointer to the Gpt configuration set
 *
 * @pre  The module shall be uninitialized
 *
 * @post The Gpt module is fully initialized and operational
 *
 * @return Std_ReturnType: E_OK if initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Gpt_Init(const Gpt_ConfigType* ConfigPtr);

/**
 * @brief De-initialize the Gpt module
 *
 * @pre  The Gpt module shall be initialized
 *
 * @post The Gpt module is de-initialized and no longer operational
 *
 * @return Std_ReturnType: E_OK if de-initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Gpt_DeInit(void);

/**
 * @brief Gpt main function - scheduled cyclic processing
 *
 * @pre  The Gpt module shall be initialized
 *
 * @post All pending Gpt processing is completed for this cycle
 *
 * @return void
 */
void Gpt_MainFunction(void);

/**
 * @brief Get the Gpt module version information
 *
 * @param [out] versioninfo  Pointer to the version information structure to be filled
 *
 * @pre  versioninfo shall not be NULL_PTR
 *
 * @post The version structure contains the Gpt module's vendor, module, and software version IDs
 *
 * @return void
 */
void Gpt_GetVersionInfo(Std_VersionInfoType* versioninfo);

/**
 * @brief Check if the Gpt module is initialized
 *
 * @return boolean: TRUE if the module is initialized, FALSE otherwise
 */
boolean Gpt_IsInitialized(void);

#endif /* ECUC_GPT_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page gpt_cfg_page Gpt Configuration
 * @brief This page documents the Gpt module configuration parameters.
 *
 * @section gpt_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Gpt AUTOSAR BSW module.
 *
 * @section gpt_cfg_usage Usage
 * Include this file in your Gpt module implementation to access
 * the configured parameters.
 *
 * @section gpt_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
