/**
 * yuleASR C Code Generator (Web Layer)
 *
 * Generates macro-only `<Module>_Cfg.h` headers for yuleASR BSW integration.
 * These are pure pre-compile configuration headers (macros only),
 * NOT AUTOSAR ECUC headers (no type definitions or function declarations).
 *
 * References:
 * - yuleASR Can_Cfg.h (config/input/mcal/Can_Cfg.h) — pure macro style
 *
 * ECUC full code generation (types + functions) is handled separately
 * by the EcucCodeGenerator in @yuletech/core.
 */

// Fix 18/22: escapeCString / C_IDENTIFIER_RE 从 core 导出，单一实现（避免 web 私有转义分叉）
import { escapeCString, C_IDENTIFIER_RE } from '@yuletech/core';
import type { ModuleSchema, ModuleParameter } from '@yuletech/core';
import { loadModuleSchemas } from '@yuletech/core/schema/load-generated';


export interface GeneratedFile {
  filename: string;
  content: string;
  language: 'c' | 'h';
}

/**
 * Well-known module configuration header names.
 * Maps module ID → expected header filename.
 */
const MODULE_HEADERS: Record<string, string> = {
  can: 'Can_Cfg.h',
  mcu: 'Mcu_Cfg.h',
  port: 'Port_Cfg.h',
  dio: 'Dio_Cfg.h',
  adc: 'Adc_Cfg.h',
  icu: 'Icu_Cfg.h',
  gpt: 'Gpt_Cfg.h',
  pwm: 'Pwm_Cfg.h',
  wdg: 'Wdg_Cfg.h',
  lin: 'Lin_Cfg.h',
  spi: 'Spi_Cfg.h',
  fr: 'Fr_Cfg.h',
  eth: 'Eth_Cfg.h',
};

/**
 * Known AUTOSAR module name aliases for header lookup.
 */
const MODULE_IDS: Record<string, number> = {
  Mcu: 43,
  Port: 42,
  Dio: 41,
  Can: 80,
  Adc: 44,
  Icu: 120,
  Gpt: 121,
  Pwm: 123,
  Wdg: 45,
  Lin: 183,
  Spi: 122,
  Fr: 46,
  Eth: 47,
};

/**
 * Get the module short name from a ConfigModule.
 * Maps module 'id' to PascalCase name (e.g. 'can' → 'Can').
 */
function getModuleShortName(id: string): string {
  // Known modules
  const known: Record<string, string> = {
    can: 'Can',
    mcu: 'Mcu',
    port: 'Port',
    dio: 'Dio',
    adc: 'Adc',
    icu: 'Icu',
    gpt: 'Gpt',
    pwm: 'Pwm',
    wdg: 'Wdg',
    lin: 'Lin',
    spi: 'Spi',
    fr: 'Fr',
    eth: 'Eth',
    os: 'Os',
    rte: 'Rte',
    // F1 CfgH-extracted 模块别名（PascalCase 头文件名/宏前缀与 snake_case id 不同）
    boot: 'Boot',
    crypto: 'Crypto',
    e2e: 'E2E',
    flash: 'Flash',
    secoc: 'SecOC',
    someip: 'SomeIp',
    tcpip: 'TcpIp',
    udpnm: 'UdpNm',
  };
  return known[id] || id.charAt(0).toUpperCase() + id.slice(1);
}

/**
 * Get the header filename for a module.
 */
function getHeaderFilename(moduleId: string): string {
  return MODULE_HEADERS[moduleId] || `${getModuleShortName(moduleId)}_Cfg.h`;
}

/**
 * Get AUTOSAR module ID number.
 */
function getModuleId(moduleName: string): number {
  return MODULE_IDS[moduleName] || 0xffff;
}

/**
 * Format a JS value as a C macro literal.
 */
function formatMacroValue(value: unknown): string {
  if (typeof value === 'boolean') {
    return value ? 'STD_ON' : 'STD_OFF';
  }
  if (typeof value === 'number') {
    if (Number.isInteger(value)) {
      return value <= 0xffff ? `(${value}U)` : `(${value}U)`;
    }
    return `${value}f`;
  }
  // Fix 18/22 (W5): 枚举标识符原样输出；自由文本加引号并转义，防止裸引号/换行注入 .h 文件
  if (typeof value === 'string') {
    return C_IDENTIFIER_RE.test(value) ? value : `"${escapeCString(value)}"`;
  }
  return String(value);
}

/**
 * Convert camelCase/snake_case to UPPER_SNAKE_CASE.
 */
function toUpperSnake(name: string): string {
  return name
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toUpperCase();
}

/**
 * Generate a macro-only `<Module>_Cfg.h` header file
 * matching yuleASR existing config header style.
 *
 * Output format follows the yuleASR convention:
 * - Doxygen-style file comment
 * - Include guard
 * - Grouped section comments with "====" style
 * - #define macros only (no type defs, no function decls)
 * - U suffix on integer literals
 */
function generateMacroOnlyHeader(
  moduleId: string,
  moduleName: string,
  moduleDisplayName: string,
  version: string,
  parameters: Record<string, unknown>,
  options: { rawMacroNames?: boolean } = {}
): string {
  const headerName = getHeaderFilename(moduleId);
  const guardName = headerName.replace(/\./g, '_').toUpperCase();
  const shortName = getModuleShortName(moduleId);
  const prefix = shortName.toUpperCase();
  const swMajor = 1;
  const swMinor = 0;
  const swPatch = 0;

  let content = `/**\n`;
  content += ` * @file ${headerName}\n`;
  content += ` * @brief ${moduleDisplayName || moduleName} configuration header\n`;
  content += ` * @version ${swMajor}.${swMinor}.${swPatch}\n`;
  content += ` * @date ${new Date().toISOString().split('T')[0]}\n`;
  content += ` * @note AUTO-GENERATED by yuleASR Configurator\n`;
  content += ` */\n\n`;

  content += `#ifndef ${guardName}\n`;
  content += `#define ${guardName}\n\n`;

  content += `/*==================================================================================================\n`;
  content += `*                                    PRE-COMPILE CONFIGURATION\n`;
  content += `*================================================================================================*/\n`;

  // Group parameters into logical sections
  const sections: Record<string, { key: string; name: string; value: unknown }[]> = {
    general: [],
    counts: [],
    baudrate: [],
    processing: [],
    controller: [],
    hoh: [],
    timeout: [],
    other: [],
  };

  for (const [key, value] of Object.entries(parameters)) {
    const keyUpper = toUpperSnake(key);
    // rawMacroNames: schema 驱动模式 — 参数名已是最终宏名（CfgH 提取），不再叠加模块前缀
    const macro = options.rawMacroNames ? key : `${prefix}_${keyUpper}`;

    // Categorize based on key name patterns
    if (/dev.?error|version.?info|det|dev/i.test(key)) {
      sections.general.push({ key, name: macro, value });
    } else if (/num_|count/i.test(keyUpper)) {
      sections.counts.push({ key, name: macro, value });
    } else if (/baud/i.test(keyUpper)) {
      sections.baudrate.push({ key, name: macro, value });
    } else if (/process|poll|interrupt/i.test(keyUpper)) {
      sections.processing.push({ key, name: macro, value });
    } else if (/controller|idx/i.test(keyUpper)) {
      sections.controller.push({ key, name: macro, value });
    } else if (/hoh|rx|tx|handle/i.test(keyUpper)) {
      sections.hoh.push({ key, name: macro, value });
    } else if (/timeout|period/i.test(keyUpper)) {
      sections.timeout.push({ key, name: macro, value });
    } else {
      sections.other.push({ key, name: macro, value });
    }
  }

  // Generate sections
  const sectionConfig: [string, string, (typeof sections)['general']][] = [
    ['GENERAL', 'General Configuration', sections.general],
    ['COUNTS', 'Module Configuration Counts', sections.counts],
    ['BAUDRATE', 'Baudrate Configurations', sections.baudrate],
    ['PROCESSING', 'Processing Modes', sections.processing],
    ['CONTROLLER', 'Controller Definitions', sections.controller],
    ['HOH', 'Hardware Object Handles', sections.hoh],
    ['TIMEOUT', 'Timing Configuration', sections.timeout],
    ['OTHER', 'Other Configuration', sections.other],
  ];

  for (const [sectionId, sectionLabel, params] of sectionConfig) {
    if (params.length === 0) continue;
    content += `\n/*==================================================================================================\n`;
    content += `*                                    ${sectionLabel}\n`;
    content += `*================================================================================================*/\n`;
    for (const p of params) {
      content += `#define ${p.name}    ${formatMacroValue(p.value)}\n`;
    }
  }

  content += `\n#endif /* ${guardName} */\n\n`;
  content += `/*==================[end of file]===========================================*/\n`;

  return content;
}

/**
 * Schema 驱动（F2a）— 参数名 → 宏名解析。
 *
 * 规则（与 yuleASR 手写 Cfg.h 对齐）：
 * 1. CfgH 提取的参数名本身就是宏名（如 FLS_CFG_VENDOR_ID）→ 原样使用；
 * 2. ARXML 风格参数名（如 WdgDisableAllowed）→ 去除模块名前缀后叠加模块前缀 → WDG_DISABLE_ALLOWED。
 */
function schemaParamToMacroName(moduleShortName: string, param: ModuleParameter): string {
  const raw = param.name;
  // 已是 UPPER_SNAKE 宏名（CfgH-Extracted: 参数名即宏名）
  if (/^[A-Z][A-Z0-9_]*$/.test(raw)) return raw;
  // 去除 PascalCase 模块名前缀，避免 WDG_WDG_* 双重前缀
  let stripped = raw;
  if (stripped.startsWith(moduleShortName) && stripped.length > moduleShortName.length) {
    stripped = stripped.slice(moduleShortName.length);
  }
  return `${moduleShortName.toUpperCase()}_${toUpperSnake(stripped)}`;
}

/**
 * Schema 驱动 — 参数默认值解析（loader 将 Cfg.h 提取值放入 default）。
 * 无 default 时按类型回落，保证所有参数都能产出合法宏值。
 */
function schemaParamValue(param: ModuleParameter): unknown {
  if (param.default !== undefined) return param.default;
  switch (param.type) {
    case 'boolean':
      return false;
    case 'integer':
    case 'float':
      return 0;
    case 'enum':
      return param.options?.[0]?.value ?? '';
    default:
      return '';
  }
}

/**
 * Schema 驱动 — 将扁平 ModuleSchema.parameters（已含递归展平的容器参数）
 * 转为宏名 → 宏值的映射。
 */
function schemaToMacroParams(moduleShortName: string, schema: ModuleSchema): Record<string, unknown> {
  const params: Record<string, unknown> = {};
  for (const p of schema.parameters || []) {
    params[schemaParamToMacroName(moduleShortName, p)] = schemaParamValue(p);
  }
  return params;
}

/**
 * Generate a macro-only Can_Cfg.h tailored for the yuleASR CAN driver.
 * Uses well-known yuleASR macros matching the existing config/input/mcal/Can_Cfg.h.
 */
function generateCanMacroHeader(
  _moduleName: string,
  _version: string,
  parameters: Record<string, unknown>
): string {
  // Extract values from parameters or use defaults matching current yuleASR config
  const devErrorDetect = parameters.devErrorDetect !== undefined ? parameters.devErrorDetect : true;
  const versionInfoApi = parameters.versionInfoApi !== undefined ? parameters.versionInfoApi : true;
  const numControllers = parameters.numControllers ?? 2;
  const numHoh = parameters.numHoh ?? 16;
  const numBaudrateConfigs = parameters.numBaudrateConfigs ?? 3;
  const timeoutDuration = parameters.timeoutDuration ?? 10000;
  const mainFunctionPeriodMs = parameters.mainFunctionPeriodMs ?? 10;

  return `/**
 * @file Can_Cfg.h
 * @brief CAN Driver configuration header
 * @version 1.0.0
 * @date ${new Date().toISOString().split('T')[0]}
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CAN_CFG_H
#define CAN_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/
#define CAN_DEV_ERROR_DETECT            ${devErrorDetect ? 'STD_ON' : 'STD_OFF'}
#define CAN_VERSION_INFO_API            ${versionInfoApi ? 'STD_ON' : 'STD_OFF'}

/*==================================================================================================
*                                    NUMBER OF CAN CONTROLLERS
*================================================================================================*/
#define CAN_NUM_CONTROLLERS             (${numControllers}U)

/*==================================================================================================
*                                    NUMBER OF HARDWARE OBJECTS
*================================================================================================*/
#define CAN_NUM_HOH                     (${numHoh}U)

/*==================================================================================================
*                                    BAUDRATE CONFIGURATIONS
*================================================================================================*/
#define CAN_NUM_BAUDRATE_CONFIGS        (${numBaudrateConfigs}U)

/* Baudrate Indexes */
#define CAN_BAUDRATE_500K               (0U)
#define CAN_BAUDRATE_250K               (1U)
#define CAN_BAUDRATE_125K               (2U)

/*==================================================================================================
*                                    PROCESSING MODES
*================================================================================================*/
#define CAN_PROCESSING_INTERRUPT        (0U)
#define CAN_PROCESSING_POLLING          (1U)

/*==================================================================================================
*                                    CONTROLLER DEFINITIONS
*================================================================================================*/
#define CAN_CONTROLLER_0                (0U)
#define CAN_CONTROLLER_1                (1U)

/*==================================================================================================
*                                    HARDWARE OBJECT HANDLES
*================================================================================================*/
#define CAN_HOH_RX_0                    ((Can_HwHandleType)0x0000U)
#define CAN_HOH_RX_1                    ((Can_HwHandleType)0x0001U)
#define CAN_HOH_RX_2                    ((Can_HwHandleType)0x0002U)
#define CAN_HOH_RX_3                    ((Can_HwHandleType)0x0003U)
#define CAN_HOH_TX_0                    ((Can_HwHandleType)0x0004U)
#define CAN_HOH_TX_1                    ((Can_HwHandleType)0x0005U)
#define CAN_HOH_TX_2                    ((Can_HwHandleType)0x0006U)
#define CAN_HOH_TX_3                    ((Can_HwHandleType)0x0007U)

/*==================================================================================================
*                                    TIMEOUT CONFIGURATION
*================================================================================================*/
#define CAN_TIMEOUT_DURATION            (${timeoutDuration}U)

/*==================================================================================================
*                                    MAIN FUNCTION PERIODS
*================================================================================================*/
#define CAN_MAIN_FUNCTION_PERIOD_MS     (${mainFunctionPeriodMs}U)

#endif /* CAN_CFG_H */
/*==================[end of file]===========================================*/
`;
}

/**
 * Generate all header files for enabled modules.
 * Returns an array of { filename, content, language } objects.
 */
export async function generateAllHeaders(
  modules: Array<{
    id: string;
    name: string;
    version: string;
    enabled: boolean;
    parameters?: Array<{ id: string; name: string; type: string; value: unknown }>;
    containers?: Array<{
      id: string;
      name: string;
      multiple?: boolean;
      parameters: Array<{ id: string; name: string; type: string; value: unknown }>;
      subContainers?: Array<{
        id: string;
        name: string;
        shortName?: string;
        parameters: Array<{ id: string; name: string; type: string; value: unknown }>;
      }>;
    }>;
    displayName?: string;
  }>
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];

  for (const module of modules) {
    if (!module.enabled) continue;

    // Extract module-level parameters as key-value pairs
    const params: Record<string, unknown> = {};
    if (module.parameters) {
      for (const p of module.parameters) {
        params[p.name] = p.value;
      }
    }

    const shortName = getModuleShortName(module.id);
    const filename = getHeaderFilename(module.id);
    let content: string;

    // Use specialized generator for CAN, else generic macro-only generator
    if (module.id === 'can') {
      content = generateCanMacroHeader(module.name, module.version, params);
    } else {
      content = generateMacroOnlyHeader(
        module.id,
        module.name,
        module.displayName || module.name,
        module.version,
        params
      );
    }

    files.push({
      filename,
      content,
      language: 'h',
    });
  }

  return files;
}

/**
 * Generate macro-only `<Module>_Cfg.h` headers from flat ModuleSchema[] (F2a).
 *
 * Schema 驱动全量生成：对任意 ModuleSchema（含 F1 从 yuleASR Cfg.h 提取的
 * 110 个模块）按 schema.parameters 生成宏头；container 参数已由 loader
 * （load-generated.ts）递归展平进 schema.parameters，生成 `PREFIX_NAME` 宏。
 *
 * 与 generateAllHeaders 的关系：
 * - generateAllHeaders 走 13 模块硬编码路径（存量，保持不变）；
 * - 本函数走 schema 驱动路径（增量），can 特例同样保留。
 * - ModuleSchema 无 enabled 字段，传入的 schema 全部生成。
 */
export async function generateHeadersFromSchemas(
  schemas: ModuleSchema[]
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];

  for (const schema of schemas) {
    const shortName = getModuleShortName(schema.name);
    const displayName = schema.label || schema.name;
    const filename = getHeaderFilename(schema.name);

    let content: string;
    if (schema.name.toLowerCase() === 'can') {
      // can 特例：需要原始参数名（devErrorDetect 等），不能叠加宏前缀
      const params: Record<string, unknown> = {};
      for (const p of schema.parameters || []) {
        params[p.name] = schemaParamValue(p);
      }
      content = generateCanMacroHeader(displayName, schema.version, params);
    } else {
      content = generateMacroOnlyHeader(schema.name, schema.name, displayName, schema.version, schemaToMacroParams(shortName, schema), {
        rawMacroNames: true,
      });
    }

    files.push({
      filename,
      content,
      language: 'h',
    });
  }

  return files;
}

/**
 * UI 层可用的最小配置模块形状（F2b：Editor 配置数据 → schema 驱动生成）。
 * 与 types/config.ts 的 ConfigModule 结构化兼容（多余字段忽略）。
 */
export interface ConfigModuleLike {
  /** 模块 id（与 name 同义，可为 undefined） */
  id?: string;
  /** 模块短名（如 'Can' / 'flash'，与 schema.name 大小写不敏感匹配） */
  name: string;
  /** 模块是否启用：仅 enabled 模块的参数值参与覆盖；禁用模块回落 schema 默认值 */
  enabled: boolean;
  /** 模块级参数（name → value；与 schema 参数名精确匹配才覆盖） */
  parameters?: Array<{ name: string; value: unknown }>;
}

/** Schema 覆盖行（F2b：模块列表页 117 模块 schema 覆盖展示） */
export interface SchemaCoverageRow {
  /** 模块名（schema 名或配置独有模块名） */
  name: string;
  /** 显示标签 */
  label?: string;
  /** 层级（MCAL/ECUAL/Service/RTE/ASW；无 schema 时为空） */
  layer?: string;
  /** 参数数（schema.parameters 长度；无 schema 时为配置参数数） */
  paramCount: number;
  /** 容器数（schema.containers 长度；无 schema 时为 0） */
  containerCount: number;
  /** 是否有 schema（有 → 可配；无 → 仅展示） */
  hasSchema: boolean;
  /** 在当前配置中的状态 */
  configStatus: 'enabled' | 'disabled' | 'absent';
}

/** 覆盖统计（覆盖表头摘要用） */
export interface SchemaCoverageSummary {
  total: number;
  withSchema: number;
  withoutSchema: number;
  configured: number;
  enabled: number;
}

/**
 * 构建 117 模块 schema 覆盖行（F2b）。
 *
 * 语义：
 * - 有 schema 且配置中存在 → 「有 schema 可配」（configStatus 区分 enabled/disabled）；
 * - 有 schema 但配置未启用/未配置 → 可配但未用；
 * - 配置中存在但无 schema → 「无 schema 仅展示」（hasSchema=false）。
 *
 * @param configModules 当前配置模块列表（可为空数组：仅展示 schema 清单）
 * @param schemas 可选 schema 列表（默认 loadModuleSchemas()，117 个）
 */
export function buildSchemaCoverage(
  configModules: ConfigModuleLike[],
  schemas?: ModuleSchema[]
): { rows: SchemaCoverageRow[]; summary: SchemaCoverageSummary } {
  const allSchemas = schemas ?? loadModuleSchemas();
  const configByName = new Map(
    configModules.map(m => [m.name.toLowerCase(), m])
  );

  const rows: SchemaCoverageRow[] = allSchemas.map(schema => {
    const cfg = configByName.get(schema.name.toLowerCase());
    return {
      name: schema.name,
      label: schema.label,
      layer: schema.layer,
      paramCount: schema.parameters?.length ?? 0,
      containerCount: schema.containers?.length ?? 0,
      hasSchema: true,
      configStatus: cfg ? (cfg.enabled ? 'enabled' : 'disabled') : 'absent',
    };
  });

  // 配置中无 schema 的模块（仅展示）
  const schemaNames = new Set(allSchemas.map(s => s.name.toLowerCase()));
  for (const cfg of configModules) {
    if (schemaNames.has(cfg.name.toLowerCase())) continue;
    rows.push({
      name: cfg.name,
      label: cfg.name,
      paramCount: cfg.parameters?.length ?? 0,
      containerCount: 0,
      hasSchema: false,
      configStatus: cfg.enabled ? 'enabled' : 'disabled',
    });
  }

  rows.sort((a, b) => a.name.localeCompare(b.name));

  const summary: SchemaCoverageSummary = {
    total: rows.length,
    withSchema: rows.filter(r => r.hasSchema).length,
    withoutSchema: rows.filter(r => !r.hasSchema).length,
    configured: rows.filter(r => r.configStatus !== 'absent').length,
    enabled: rows.filter(r => r.configStatus === 'enabled').length,
  };

  return { rows, summary };
}

/**
 * 配置数据 → schema 驱动全量生成（F2b 主入口）。
 *
 * 将 Editor 配置模块的参数值覆盖到对应 schema 的 default 上（按参数名精确匹配），
 * 然后走 F2a 的 generateHeadersFromSchemas 生成全部模块 `<Module>_Cfg.h`。
 *
 * 规则（诚实声明）：
 * - 生成集合 = 全部 schema（117 个），不因配置未启用而跳过——yuleASR 构建需要全量头文件；
 * - 仅 enabled 配置模块的参数参与覆盖；disabled/未配置模块按 schema 默认值生成；
 * - 配置参数名与 schema 参数名精确匹配（区分大小写）；不匹配的参数不影响该模块生成；
 * - 配置中存在但 schema 缺失的模块不参与生成（无 schema 无法生成宏头，仅覆盖表展示）。
 *
 * @param configModules 当前配置模块
 * @param schemas 可选 schema 列表（默认 loadModuleSchemas()）
 * @returns 全部模块生成文件（与 schemas 等长）
 */
export async function generateHeadersFromConfig(
  configModules: ConfigModuleLike[],
  schemas?: ModuleSchema[]
): Promise<GeneratedFile[]> {
  const allSchemas = schemas ?? loadModuleSchemas();
  const configByModule = new Map(
    configModules
      .filter(m => m.enabled)
      .map(m => [m.name.toLowerCase(), m])
  );

  const overridden = allSchemas.map(schema => {
    const cfg = configByModule.get(schema.name.toLowerCase());
    if (!cfg) return schema;
    const cfgParams = new Map((cfg.parameters ?? []).map(p => [p.name, p.value]));
    return {
      ...schema,
      parameters: (schema.parameters ?? []).map(p =>
        cfgParams.has(p.name) ? { ...p, default: cfgParams.get(p.name) } : p
      ),
    };
  });

  return generateHeadersFromSchemas(overridden);
}

/**
 * Generate a single module header file.
 * Returns null if the module is disabled.
 */
export async function generateHeader(
  module: {
    id: string;
    name: string;
    version: string;
    enabled: boolean;
    parameters?: Array<{ id: string; name: string; type: string; value: unknown }>;
    containers?: Array<{
      id: string;
      name: string;
      multiple?: boolean;
      parameters: Array<{ id: string; name: string; type: string; value: unknown }>;
      subContainers?: Array<{
        id: string;
        name: string;
        shortName?: string;
        parameters: Array<{ id: string; name: string; type: string; value: unknown }>;
      }>;
    }>;
    displayName?: string;
  }
): Promise<GeneratedFile | null> {
  if (!module.enabled) return null;

  const files = await generateAllHeaders([module]);
  return files[0] || null;
}
