/**
 * yuleASR C Code Generator (Web Layer)
 *
 * Generates macro-only `<Module>_Cfg.h` headers for yuleASR BSW integration.
 * These are pure pre-compile configuration headers (macros only),
 * NOT AUTOSAR ECUC headers (no type definitions or function declarations).
 *
 * References:
 * - yuleASR Can_Cfg.h (config/input/mcal/Can_Cfg.h) — pure macro style
 *
 * ECUC full code generation (types + functions) is handled separately
 * by the EcucCodeGenerator in @yuletech/core.
 */

export interface GeneratedFile {
  filename: string;
  content: string;
  language: 'c' | 'h';
}

/**
 * Well-known module configuration header names.
 * Maps module ID → expected header filename.
 */
const MODULE_HEADERS: Record<string, string> = {
  can: 'Can_Cfg.h',
  mcu: 'Mcu_Cfg.h',
  port: 'Port_Cfg.h',
  dio: 'Dio_Cfg.h',
  adc: 'Adc_Cfg.h',
  icu: 'Icu_Cfg.h',
  gpt: 'Gpt_Cfg.h',
  pwm: 'Pwm_Cfg.h',
  wdg: 'Wdg_Cfg.h',
  lin: 'Lin_Cfg.h',
  spi: 'Spi_Cfg.h',
  fr: 'Fr_Cfg.h',
  eth: 'Eth_Cfg.h',
};

/**
 * Known AUTOSAR module name aliases for header lookup.
 */
const MODULE_IDS: Record<string, number> = {
  Mcu: 43,
  Port: 42,
  Dio: 41,
  Can: 80,
  Adc: 44,
  Icu: 120,
  Gpt: 121,
  Pwm: 123,
  Wdg: 45,
  Lin: 183,
  Spi: 122,
  Fr: 46,
  Eth: 47,
};

/**
 * Get the module short name from a ConfigModule.
 * Maps module 'id' to PascalCase name (e.g. 'can' → 'Can').
 */
function getModuleShortName(id: string): string {
  // Known modules
  const known: Record<string, string> = {
    can: 'Can',
    mcu: 'Mcu',
    port: 'Port',
    dio: 'Dio',
    adc: 'Adc',
    icu: 'Icu',
    gpt: 'Gpt',
    pwm: 'Pwm',
    wdg: 'Wdg',
    lin: 'Lin',
    spi: 'Spi',
    fr: 'Fr',
    eth: 'Eth',
    os: 'Os',
    rte: 'Rte',
  };
  return known[id] || id.charAt(0).toUpperCase() + id.slice(1);
}

/**
 * Get the header filename for a module.
 */
function getHeaderFilename(moduleId: string): string {
  return MODULE_HEADERS[moduleId] || `${getModuleShortName(moduleId)}_Cfg.h`;
}

/**
 * Get AUTOSAR module ID number.
 */
function getModuleId(moduleName: string): number {
  return MODULE_IDS[moduleName] || 0xffff;
}

/**
 * Format a JS value as a C macro literal.
 */
function formatMacroValue(value: unknown): string {
  if (typeof value === 'boolean') {
    return value ? 'STD_ON' : 'STD_OFF';
  }
  if (typeof value === 'number') {
    if (Number.isInteger(value)) {
      return value <= 0xffff ? `(${value}U)` : `(${value}U)`;
    }
    return `${value}f`;
  }
  if (typeof value === 'string') return value;
  return String(value);
}

/**
 * Convert camelCase/snake_case to UPPER_SNAKE_CASE.
 */
function toUpperSnake(name: string): string {
  return name
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toUpperCase();
}

/**
 * Generate a macro-only `<Module>_Cfg.h` header file
 * matching yuleASR existing config header style.
 *
 * Output format follows the yuleASR convention:
 * - Doxygen-style file comment
 * - Include guard
 * - Grouped section comments with "====" style
 * - #define macros only (no type defs, no function decls)
 * - U suffix on integer literals
 */
function generateMacroOnlyHeader(
  moduleId: string,
  moduleName: string,
  moduleDisplayName: string,
  version: string,
  parameters: Record<string, unknown>
): string {
  const headerName = getHeaderFilename(moduleId);
  const guardName = headerName.replace(/\./g, '_').toUpperCase();
  const shortName = getModuleShortName(moduleId);
  const prefix = shortName.toUpperCase();
  const swMajor = 1;
  const swMinor = 0;
  const swPatch = 0;

  let content = `/**\n`;
  content += ` * @file ${headerName}\n`;
  content += ` * @brief ${moduleDisplayName || moduleName} configuration header\n`;
  content += ` * @version ${swMajor}.${swMinor}.${swPatch}\n`;
  content += ` * @date ${new Date().toISOString().split('T')[0]}\n`;
  content += ` * @note AUTO-GENERATED by yuleASR Configurator\n`;
  content += ` */\n\n`;

  content += `#ifndef ${guardName}\n`;
  content += `#define ${guardName}\n\n`;

  content += `/*==================================================================================================\n`;
  content += `*                                    PRE-COMPILE CONFIGURATION\n`;
  content += `*================================================================================================*/\n`;

  // Group parameters into logical sections
  const sections: Record<string, { key: string; name: string; value: unknown }[]> = {
    general: [],
    counts: [],
    baudrate: [],
    processing: [],
    controller: [],
    hoh: [],
    timeout: [],
    other: [],
  };

  for (const [key, value] of Object.entries(parameters)) {
    const keyUpper = toUpperSnake(key);
    const macro = `${prefix}_${keyUpper}`;

    // Categorize based on key name patterns
    if (/dev.?error|version.?info|det|dev/i.test(key)) {
      sections.general.push({ key, name: macro, value });
    } else if (/num_|count/i.test(keyUpper)) {
      sections.counts.push({ key, name: macro, value });
    } else if (/baud/i.test(keyUpper)) {
      sections.baudrate.push({ key, name: macro, value });
    } else if (/process|poll|interrupt/i.test(keyUpper)) {
      sections.processing.push({ key, name: macro, value });
    } else if (/controller|idx/i.test(keyUpper)) {
      sections.controller.push({ key, name: macro, value });
    } else if (/hoh|rx|tx|handle/i.test(keyUpper)) {
      sections.hoh.push({ key, name: macro, value });
    } else if (/timeout|period/i.test(keyUpper)) {
      sections.timeout.push({ key, name: macro, value });
    } else {
      sections.other.push({ key, name: macro, value });
    }
  }

  // Generate sections
  const sectionConfig: [string, string, (typeof sections)['general']][] = [
    ['GENERAL', 'General Configuration', sections.general],
    ['COUNTS', 'Module Configuration Counts', sections.counts],
    ['BAUDRATE', 'Baudrate Configurations', sections.baudrate],
    ['PROCESSING', 'Processing Modes', sections.processing],
    ['CONTROLLER', 'Controller Definitions', sections.controller],
    ['HOH', 'Hardware Object Handles', sections.hoh],
    ['TIMEOUT', 'Timing Configuration', sections.timeout],
    ['OTHER', 'Other Configuration', sections.other],
  ];

  for (const [sectionId, sectionLabel, params] of sectionConfig) {
    if (params.length === 0) continue;
    content += `\n/*==================================================================================================\n`;
    content += `*                                    ${sectionLabel}\n`;
    content += `*================================================================================================*/\n`;
    for (const p of params) {
      content += `#define ${p.name}    ${formatMacroValue(p.value)}\n`;
    }
  }

  content += `\n#endif /* ${guardName} */\n\n`;
  content += `/*==================[end of file]===========================================*/\n`;

  return content;
}

/**
 * Generate a macro-only Can_Cfg.h tailored for the yuleASR CAN driver.
 * Uses well-known yuleASR macros matching the existing config/input/mcal/Can_Cfg.h.
 */
function generateCanMacroHeader(
  _moduleName: string,
  _version: string,
  parameters: Record<string, unknown>
): string {
  // Extract values from parameters or use defaults matching current yuleASR config
  const devErrorDetect = parameters.devErrorDetect !== undefined ? parameters.devErrorDetect : true;
  const versionInfoApi = parameters.versionInfoApi !== undefined ? parameters.versionInfoApi : true;
  const numControllers = parameters.numControllers ?? 2;
  const numHoh = parameters.numHoh ?? 16;
  const numBaudrateConfigs = parameters.numBaudrateConfigs ?? 3;
  const timeoutDuration = parameters.timeoutDuration ?? 10000;
  const mainFunctionPeriodMs = parameters.mainFunctionPeriodMs ?? 10;

  return `/**
 * @file Can_Cfg.h
 * @brief CAN Driver configuration header
 * @version 1.0.0
 * @date ${new Date().toISOString().split('T')[0]}
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CAN_CFG_H
#define CAN_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/
#define CAN_DEV_ERROR_DETECT            ${devErrorDetect ? 'STD_ON' : 'STD_OFF'}
#define CAN_VERSION_INFO_API            ${versionInfoApi ? 'STD_ON' : 'STD_OFF'}

/*==================================================================================================
*                                    NUMBER OF CAN CONTROLLERS
*================================================================================================*/
#define CAN_NUM_CONTROLLERS             (${numControllers}U)

/*==================================================================================================
*                                    NUMBER OF HARDWARE OBJECTS
*================================================================================================*/
#define CAN_NUM_HOH                     (${numHoh}U)

/*==================================================================================================
*                                    BAUDRATE CONFIGURATIONS
*================================================================================================*/
#define CAN_NUM_BAUDRATE_CONFIGS        (${numBaudrateConfigs}U)

/* Baudrate Indexes */
#define CAN_BAUDRATE_500K               (0U)
#define CAN_BAUDRATE_250K               (1U)
#define CAN_BAUDRATE_125K               (2U)

/*==================================================================================================
*                                    PROCESSING MODES
*================================================================================================*/
#define CAN_PROCESSING_INTERRUPT        (0U)
#define CAN_PROCESSING_POLLING          (1U)

/*==================================================================================================
*                                    CONTROLLER DEFINITIONS
*================================================================================================*/
#define CAN_CONTROLLER_0                (0U)
#define CAN_CONTROLLER_1                (1U)

/*==================================================================================================
*                                    HARDWARE OBJECT HANDLES
*================================================================================================*/
#define CAN_HOH_RX_0                    ((Can_HwHandleType)0x0000U)
#define CAN_HOH_RX_1                    ((Can_HwHandleType)0x0001U)
#define CAN_HOH_RX_2                    ((Can_HwHandleType)0x0002U)
#define CAN_HOH_RX_3                    ((Can_HwHandleType)0x0003U)
#define CAN_HOH_TX_0                    ((Can_HwHandleType)0x0004U)
#define CAN_HOH_TX_1                    ((Can_HwHandleType)0x0005U)
#define CAN_HOH_TX_2                    ((Can_HwHandleType)0x0006U)
#define CAN_HOH_TX_3                    ((Can_HwHandleType)0x0007U)

/*==================================================================================================
*                                    TIMEOUT CONFIGURATION
*================================================================================================*/
#define CAN_TIMEOUT_DURATION            (${timeoutDuration}U)

/*==================================================================================================
*                                    MAIN FUNCTION PERIODS
*================================================================================================*/
#define CAN_MAIN_FUNCTION_PERIOD_MS     (${mainFunctionPeriodMs}U)

#endif /* CAN_CFG_H */
/*==================[end of file]===========================================*/
`;
}

/**
 * Generate all header files for enabled modules.
 * Returns an array of { filename, content, language } objects.
 */
export async function generateAllHeaders(
  modules: Array<{
    id: string;
    name: string;
    version: string;
    enabled: boolean;
    parameters?: Array<{ id: string; name: string; type: string; value: unknown }>;
    containers?: Array<{
      id: string;
      name: string;
      multiple?: boolean;
      parameters: Array<{ id: string; name: string; type: string; value: unknown }>;
      subContainers?: Array<{
        id: string;
        name: string;
        shortName?: string;
        parameters: Array<{ id: string; name: string; type: string; value: unknown }>;
      }>;
    }>;
    displayName?: string;
  }>
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];

  for (const module of modules) {
    if (!module.enabled) continue;

    // Extract module-level parameters as key-value pairs
    const params: Record<string, unknown> = {};
    if (module.parameters) {
      for (const p of module.parameters) {
        params[p.name] = p.value;
      }
    }

    const shortName = getModuleShortName(module.id);
    const filename = getHeaderFilename(module.id);
    let content: string;

    // Use specialized generator for CAN, else generic macro-only generator
    if (module.id === 'can') {
      content = generateCanMacroHeader(module.name, module.version, params);
    } else {
      content = generateMacroOnlyHeader(
        module.id,
        module.name,
        module.displayName || module.name,
        module.version,
        params
      );
    }

    files.push({
      filename,
      content,
      language: 'h',
    });
  }

  return files;
}

/**
 * Generate a single module header file.
 * Returns null if the module is disabled.
 */
export async function generateHeader(
  module: {
    id: string;
    name: string;
    version: string;
    enabled: boolean;
    parameters?: Array<{ id: string; name: string; type: string; value: unknown }>;
    containers?: Array<{
      id: string;
      name: string;
      multiple?: boolean;
      parameters: Array<{ id: string; name: string; type: string; value: unknown }>;
      subContainers?: Array<{
        id: string;
        name: string;
        shortName?: string;
        parameters: Array<{ id: string; name: string; type: string; value: unknown }>;
      }>;
    }>;
    displayName?: string;
  }
): Promise<GeneratedFile | null> {
  if (!module.enabled) return null;

  const files = await generateAllHeaders([module]);
  return files[0] || null;
}
