/**
 * AUTOSAR C Header Code Generator
 * Generates _Cfg.h files from ConfigModule data
 * Zero external dependencies
 */

import type { ConfigModule, ConfigContainer, ConfigParameter } from '@/types/config'

export interface GeneratedFile {
  filename: string
  content: string
  language: 'c' | 'h'
}

// ---- Module name to standard header mapping ----
const MODULE_HEADERS: Record<string, string> = {
  adc: 'Adc_Cfg.h',
  can: 'Can_Cfg.h',
  cantrcv: 'CanTrcv_Cfg.h',
  dio: 'Dio_Cfg.h',
  gpt: 'Gpt_Cfg.h',
  icu: 'Icu_Cfg.h',
  mcu: 'Mcu_Cfg.h',
  port: 'Port_Cfg.h',
  spi: 'Spi_Cfg.h',
  mcl: 'Mcl_Cfg.h',
  dcm: 'Dcm_Cfg.h',
  nvm: 'NvM_Cfg.h',
  ecum: 'EcuM_Cfg.h',
  com: 'Com_Cfg.h',
}

/**
 * Main entry point: generate all _Cfg.h files for enabled modules
 */
export function generateAllHeaders(modules: ConfigModule[]): GeneratedFile[] {
  const files: GeneratedFile[] = []

  for (const module of modules) {
    if (!module.enabled) continue

    const headerName = MODULE_HEADERS[module.id]
    if (!headerName) continue

    const generator = GENERATORS[module.id]
    if (!generator) continue

    const content = generator(module)
    files.push({ filename: headerName, content, language: 'h' })
  }

  return files
}

/**
 * Generate a single header file for a specific module
 */
export function generateHeader(module: ConfigModule): GeneratedFile | null {
  const headerName = MODULE_HEADERS[module.id]
  if (!headerName) return null

  const generator = GENERATORS[module.id]
  if (!generator) return null

  return { filename: headerName, content: generator(module), language: 'h' }
}

// ---- Helper utilities ----

function getContainerParam(container: ConfigContainer, paramId: string): ConfigParameter | undefined {
  return container.parameters.find(p => p.id === paramId || p.name === paramId)
}

function getContainerValue(container: ConfigContainer, paramId: string, defaultValue: any = ''): any {
  const param = getContainerParam(container, paramId)
  return param?.value ?? defaultValue
}

function formatValue(val: any, type?: string): string {
  if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE'
  if (typeof val === 'number' && type === 'float') return `${val}f`
  if (typeof val === 'number') return `${val}U`
  if (typeof val === 'string') return val
  return String(val)
}

function toDefineName(name: string): string {
  return name
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toUpperCase()
}

function toGuardName(filename: string): string {
  return filename.replace(/\./g, '_').toUpperCase()
}

// ---- Type for generator functions ----
type GeneratorFn = (module: ConfigModule) => string

// ---- Generator: Adc_Cfg.h ----
function generateAdcCfg(module: ConfigModule): string {
  const guard = toGuardName('Adc_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR ADC Driver Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `/* Module Version */`,
    `#define ADC_MODULE_ID           ${module.version || '44'}`,
    `#define ADC_VENDOR_ID           123`,
    ``,
  ]

  // Find AdcConfigSet container
  const configSet = module.containers.find(c => c.id === 'adcconfigset')
  if (!configSet || !configSet.subContainers?.length) {
    lines.push(`/* No ADC HW units configured */`)
  } else {
    // Get dynamic instances OR static subContainers
    const instances = configSet.subContainers.filter(c => c.id.startsWith('adchwunit'))
    const hwUnits = instances.length > 0 ? instances : configSet.subContainers.filter(c => c.name?.toLowerCase().includes('hwu'))
    
    lines.push(`/* ADC HW Unit Count */`)
    lines.push(`#define ADC_MAX_HW_UNIT_COUNT      ${hwUnits.length}U`)
    lines.push(``)

    hwUnits.forEach((unit, idx) => {
      const doze = getContainerValue(unit, 'adcdozemode', false)
      const hwId = getContainerValue(unit, 'adchwunitid', `ADC${idx}`)
      const resolution = getContainerValue(unit, 'adcresolution', 'BITS_12')
      const transferType = getContainerValue(unit, 'adctransfertype', 'ADC_INTERRUPT')

      lines.push(`/* ${unit.name} */`)
      lines.push(`#define ADC_${idx}_DOZE_MODE            ${formatValue(doze)}`)
      lines.push(`#define ADC_${idx}_HW_UNIT_ID           ${hwId}`)
      lines.push(`#define ADC_${idx}_RESOLUTION           ${resolution}`)
      lines.push(`#define ADC_${idx}_TRANSFER_TYPE        ${transferType}`)
      
      // Channels
      const channels = unit.subContainers?.filter(c => c.id.startsWith('adcchannel')) || []
      if (channels.length > 0) {
        lines.push(`#define ADC_${idx}_CHANNEL_COUNT       ${channels.length}U`)
        channels.forEach((ch, chIdx) => {
          const chId = getContainerValue(ch, 'adcchannelid', 'CH_NONE')
          const sampleTime = getContainerValue(ch, 'adcsampletimeselect', 'SAMPLE_TIME_DEFAULT')
          lines.push(`#define ADC_${idx}_CH_${chIdx}_ID              ${chId}`)
          lines.push(`#define ADC_${idx}_CH_${chIdx}_SAMPLE_TIME     ${sampleTime}`)
        })
      }
      
      // Groups
      const groups = unit.subContainers?.filter(c => c.id.startsWith('adcgroup')) || []
      if (groups.length > 0) {
        groups.forEach((grp, gIdx) => {
          const accessMode = getContainerValue(grp, 'adcgroupaccessmode', 'ACCESS_SINGLE')
          lines.push(`#define ADC_${idx}_GROUP_${gIdx}_ACCESS_MODE   ${accessMode}`)
        })
      }
      lines.push(``)
    })
  }

  lines.push(`#endif /* ${guard} */`)
  lines.push(``)
  return lines.join('\n')
}

// ---- Generator: Mcu_Cfg.h ----
function generateMcuCfg(module: ConfigModule): string {
  const guard = toGuardName('Mcu_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR MCU Driver Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `/* Module Version */`,
    `#define MCU_MODULE_ID            43`,
    `#define MCU_VENDOR_ID            123`,
    ``,
  ]

  // McuGeneral
  const general = module.containers.find(c => c.id.includes('general'))
  if (general) {
    const versionInfo = getContainerValue(general, 'mcudevinfodetection', false)
    const ramSectors = getContainerValue(general, 'mcuramsectors', 0)
    lines.push(`/* General */`)
    lines.push(`#define MCU_DEV_ERROR_DETECT       ${formatValue(versionInfo)}`)
    lines.push(`#define MCU_RAM_SECTIONS           ${formatValue(ramSectors)}`)
    lines.push(``)
  }

  // McuClockSetting
  const clockSetting = module.containers.find(c => c.id === 'mcuclocksetting')
  if (clockSetting) {
    const clockConfigs = clockSetting.subContainers?.filter(c => c.name?.toLowerCase().includes('mode')) || []
    lines.push(`/* Clock Settings */`)
    lines.push(`#define MCU_NUMBER_OF_CLOCK_SETTINGS  ${clockConfigs.length}U`)
    clockConfigs.forEach((cfg, idx) => {
      const coreClock = getContainerValue(cfg, 'mcucoreclock', 96000000)
      const pllRef = getContainerValue(cfg, 'mcupllrefclk', 8000000)
      lines.push(`#define MCU_CLOCK_SETTING_${idx}         ${coreClock}U`)
      lines.push(`#define MCU_CLOCK_${idx}_PLL_REF         ${pllRef}U`)
    })
    lines.push(``)
  }

  lines.push(`#endif /* ${guard} */`)
  lines.push(``)
  return lines.join('\n')
}

// ---- Generator: Can_Cfg.h ----
function generateCanCfg(module: ConfigModule): string {
  const guard = toGuardName('Can_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR CAN Driver Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `/* Module Version */`,
    `#define CAN_MODULE_ID             80`,
    `#define CAN_VENDOR_ID             123`,
    ``,
  ]

  // CanGeneral
  const general = module.containers.find(c => c.id.includes('general'))
  if (general) {
    const devErr = getContainerValue(general, 'candeverrordetect', false)
    const verInfo = getContainerValue(general, 'canversioninfoapi', false)
    lines.push(`/* General */`)
    lines.push(`#define CAN_DEV_ERROR_DETECT       ${formatValue(devErr)}`)
    lines.push(`#define CAN_VERSION_INFO_API       ${formatValue(verInfo)}`)
    lines.push(``)
  }

  // CanConfigSet
  const configSet = module.containers.find(c => c.id === 'canconfigset')
  if (configSet?.subContainers?.length) {
    const controllers = configSet.subContainers.filter(c => c.name?.toLowerCase().includes('controller') || c.id.startsWith('cancontroller'))
    lines.push(`/* CAN Controllers */`)
    lines.push(`#define CAN_CONTROLLER_COUNT       ${controllers.length}U`)
    controllers.forEach((ctrl, idx) => {
      const baudrate = getContainerValue(ctrl, 'canbaudrate', 500000)
      lines.push(`#define CAN_${idx}_BAUDRATE             ${baudrate}U`)

      // Filter masks
      const filters = ctrl.subContainers?.filter(c => c.name?.toLowerCase().includes('filter') || c.id.includes('mask')) || []
      filters.forEach((f, fIdx) => {
        const mask = getContainerValue(f, 'canfiltermask', 0)
        lines.push(`#define CAN_${idx}_FILTER_${fIdx}_MASK  0x${Number(mask).toString(16)}`)
      })
    })
    lines.push(``)
  }

  lines.push(`#endif /* ${guard} */`)
  lines.push(``)
  return lines.join('\n')
}

// ---- Generator: Port_Cfg.h ----
function generatePortCfg(module: ConfigModule): string {
  const guard = toGuardName('Port_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR PORT Driver Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `#define PORT_MODULE_ID            42`,
    `#define PORT_VENDOR_ID            123`,
    ``,
  ]

  // PortConfigSet
  const configSet = module.containers.find(c => c.id === 'portconfigset')
  if (configSet?.subContainers?.length) {
    const containers = configSet.subContainers.filter(c => c.id.startsWith('portcontainer'))
    containers.forEach((cont, idx) => {
      const pins = cont.subContainers?.filter(c => c.id.startsWith('portpin')) || []
      pins.forEach((pin, pIdx) => {
        const pinId = getContainerValue(pin, 'portpinid', 0)
        const direction = getContainerValue(pin, 'portpindirection', 'PORT_PIN_IN')
        const mode = getContainerValue(pin, 'portpinmode', 'PORT_PIN_MODE_GPIO')
        lines.push(`/* ${pin.name} */`)
        lines.push(`#define PORT_${idx}_PIN_${pIdx}_ID        ${pinId}U`)
        lines.push(`#define PORT_${idx}_PIN_${pIdx}_DIR       ${direction}`)
        lines.push(`#define PORT_${idx}_PIN_${pIdx}_MODE      ${mode}`)
      })
    })
    lines.push(``)
  }

  lines.push(`#endif /* ${guard} */`)
  return lines.join('\n')
}

// ---- Generator: Dio_Cfg.h ----
function generateDioCfg(module: ConfigModule): string {
  const guard = toGuardName('Dio_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR DIO Driver Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `#define DIO_MODULE_ID             41`,
    `#define DIO_VENDOR_ID             123`,
    ``,
  ]

  // DioConfig
  const dioConfig = module.containers.find(c => c.id === 'dioconfig')
  if (dioConfig) {
    const portIds = dioConfig.parameters.filter(p => p.name?.includes('PortId') || p.name?.includes('portid'))
    const channels = dioConfig.parameters.filter(p => p.name?.includes('ChannelId') || p.name?.includes('channelid'))
    lines.push(`#define DIO_NUMBER_OF_PORTS       ${portIds.length}U`)
    lines.push(`#define DIO_NUMBER_OF_CHANNELS    ${channels.length}U`)
    lines.push(``)
  }

  lines.push(`#endif /* ${guard} */`)
  return lines.join('\n')
}

// ---- Generator: Icu_Cfg.h ----
function generateIcuCfg(module: ConfigModule): string {
  const guard = toGuardName('Icu_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR ICU Driver Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `#define ICU_MODULE_ID             120`,
    `#define ICU_VENDOR_ID             123`,
    ``,
  ]

  // IcuConfigSet
  const configSet = module.containers.find(c => c.id === 'icuconfigset')
  if (configSet?.subContainers?.length) {
    const channels = configSet.subContainers.filter(c => c.id.startsWith('icuchannel'))
    lines.push(`/* ICU Channels */`)
    lines.push(`#define ICU_CHANNEL_COUNT         ${channels.length}U`)
    channels.forEach((ch, idx) => {
      const chId = getContainerValue(ch, 'icuchannelid', 0)
      const edgeDetect = getContainerValue(ch, 'icusignaledgedetection', 'ICU_BOTH_EDGES')
      lines.push(`#define ICU_${idx}_CHANNEL_ID           ${chId}U`)
      lines.push(`#define ICU_${idx}_EDGE_DETECTION       ${edgeDetect}`)
    })
    lines.push(``)
  }

  lines.push(`#endif /* ${guard} */`)
  return lines.join('\n')
}

// ---- Generator: Gpt_Cfg.h ----
function generateGptCfg(module: ConfigModule): string {
  const guard = toGuardName('Gpt_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR GPT Driver Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `#define GPT_MODULE_ID             121`,
    `#define GPT_VENDOR_ID             123`,
    ``,
  ]

  // GptChannelConfigSet
  const configSet = module.containers.find(c => c.id === 'gptchannelconfigset')
  if (configSet?.subContainers?.length) {
    const channels = configSet.subContainers.filter(c => c.name?.toLowerCase().includes('channelconfiguration'))
    lines.push(`/* GPT Channels */`)
    lines.push(`#define GPT_CHANNEL_COUNT         ${channels.length}U`)
    channels.forEach((ch, idx) => {
      const tickFreq = getContainerValue(ch, 'gpttickfrequency', 1000)
      const chMode = getContainerValue(ch, 'gptchannelmode', 'GPT_CH_MODE_ONESHOT')
      lines.push(`#define GPT_${idx}_TICK_FREQUENCY       ${tickFreq}U`)
      lines.push(`#define GPT_${idx}_CHANNEL_MODE         ${chMode}`)
    })
    lines.push(``)
  }

  lines.push(`#endif /* ${guard} */`)
  return lines.join('\n')
}

// ---- Generator: Spi_Cfg.h ----
function generateSpiCfg(module: ConfigModule): string {
  const guard = toGuardName('Spi_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR SPI Driver Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `#define SPI_MODULE_ID             122`,
    `#define SPI_VENDOR_ID             123`,
    ``,
  ]

  // SpiChannelList
  const chanList = module.containers.find(c => c.id === 'spichannellist_0' || c.id.startsWith('spichannellist'))
  if (chanList?.subContainers?.length) {
    const channels = chanList.subContainers.filter(c => c.id.startsWith('spichannel'))
    lines.push(`/* SPI Channels */`)
    lines.push(`#define SPI_CHANNEL_COUNT         ${channels.length}U`)
    channels.forEach((ch, idx) => {
      const id = getContainerValue(ch, 'spichannelid', idx)
      const baudrate = getContainerValue(ch, 'spi_bittate', 1000000)
      lines.push(`#define SPI_${idx}_ID                  ${id}U`)
      lines.push(`#define SPI_${idx}_BAUDRATE            ${baudrate}U`)
    })
    lines.push(``)
  }

  // SpiExternalDevice
  const extDevices = module.containers.filter(c => c.id.startsWith('spiexternaldevice'))
  if (extDevices.length > 0) {
    lines.push(`/* External Devices */`)
    extDevices.forEach((dev, idx) => {
      const cs = getContainerValue(dev, 'spichipselect', 0)
      lines.push(`#define SPI_DEV_${idx}_CHIP_SELECT       ${cs}U`)
    })
    lines.push(``)
  }

  lines.push(`#endif /* ${guard} */`)
  return lines.join('\n')
}

// ---- Generator: NvM_Cfg.h ----
function generateNvmCfg(module: ConfigModule): string {
  const guard = toGuardName('NvM_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR NvM Manager Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `#define NVM_MODULE_ID             150`,
    `#define NVM_VENDOR_ID             123`,
    ``,

    `#define NVM_MAX_NUM_OF_BLOCKS     0U`,
    `#define NVM_DEV_ERROR_DETECT      ${formatValue(getContainerParam(module.containers.find(c => c.id.includes('general')) || { id: '', name: '', parameters: [], subContainers: [] }, 'nvmdeverrordetect')?.value ?? false)}`,
    ``,
    `#endif /* ${guard} */`,
    ``,
  ]
  return lines.join('\n')
}

// ---- Generator: EcuM_Cfg.h ----
function generateEcuMCfg(module: ConfigModule): string {
  const guard = toGuardName('EcuM_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR ECU Manager Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `#define ECUM_MODULE_ID            151`,
    `#define ECUM_VENDOR_ID            123`,
    ``,
    `#define ECUM_DEV_ERROR_DETECT     ${formatValue(getContainerParam(module.containers.find(c => c.id.includes('general')) || { id: '', name: '', parameters: [], subContainers: [] }, 'ecumdeverrordetect')?.value ?? false)}`,
    ``,
    `#endif /* ${guard} */`,
    ``,
  ]
  return lines.join('\n')
}

// ---- Generator: CanTrcv_Cfg.h ----
function generateCanTrcvCfg(module: ConfigModule): string {
  const guard = toGuardName('CanTrcv_Cfg.h')
  const lines: string[] = [
    `/* AUTOSAR CAN Transceiver Driver Configuration */`,
    `/* Generated by yuleASR Configurator */`,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    ``,
    `#define CANTRCV_MODULE_ID         81`,
    `#define CANTRCV_VENDOR_ID         123`,
    ``,
  ]

  const configSet = module.containers.find(c => c.id === 'cantrcv_configset')
  if (configSet?.subContainers?.length) {
    const trcvControllers = configSet.subContainers.filter(c => c.id.startsWith('cantrcv_controller') || c.id.startsWith('cantrcv'))
    lines.push(`#define CANTRCV_TRCV_COUNT       ${trcvControllers.length}U`)
    trcvControllers.forEach((trcv, idx) => {
      const wakupSrc = getContainerValue(trcv, 'cantrcvwakeupsource', 'CANTRCV_NO_WAKEUP')
      lines.push(`#define CANTRCV_${idx}_WAKEUP_SOURCE     ${wakupSrc}`)
    })
    lines.push(``)
  }

  lines.push(`#endif /* ${guard} */`)
  return lines.join('\n')
}

// ---- Generator registry ----
const GENERATORS: Record<string, GeneratorFn> = {
  adc: generateAdcCfg,
  mcu: generateMcuCfg,
  can: generateCanCfg,
  port: generatePortCfg,
  dio: generateDioCfg,
  icu: generateIcuCfg,
  gpt: generateGptCfg,
  spi: generateSpiCfg,
  cantrcv: generateCanTrcvCfg,
  nvm: generateNvmCfg,
  ecum: generateEcuMCfg,
}
