// ==================================================================
// Example: CustomHeaderGenerator
// Type: code-generator
//
// A plugin that wraps generated C files with a custom copyright
// header. Demonstrates:
//   - YulePlugin.activate()
//   - PluginContext.registerCodeGenerator()
//   - CodeGeneratorPlugin.generate()
//   - Reading user config (context.config)
// ==================================================================

import type {
  YulePlugin,
  PluginContext,
  CodeGeneratorPlugin,
} from '@yuletech/plugin-sdk';

/**
 * Creates a formatted copyright header block.
 */
function buildCopyrightHeader(
  company: string,
  author: string,
  license: string,
  year: number,
): string {
  return `\
/*
 * ==================================================================
 * Copyright (c) ${year} ${company}
 * All rights reserved.
 *
 * Author: ${author}
 * License: ${license}
 *
 * This file is auto-generated by the yuleASR Configurator.
 * Do NOT edit manually — changes will be overwritten.
 * ==================================================================
 */

`;
}

/**
 * Custom Header Generator Plugin
 *
 * This is a 'universal' code generator (supportedModules = ['*']) that
 * prepends a copyright header to any generated C file. The header content
 * is controlled via the plugin's user configuration.
 *
 * User config options (set via PUT /v1/api/plugins/:id/config):
 *   - company (string, default: "YuleTech")
 *   - author  (string, default: "yuleASR Team")
 *   - license (string, default: "Proprietary")
 */
const customHeaderGenerator: YulePlugin = {
  id: 'example-custom-header-generator',
  name: 'Custom Header Generator',
  version: '1.0.0',
  type: 'code-generator',
  description:
    'Prepends a configurable copyright header to generated C source and header files',
  author: 'YuleTech Examples',

  async activate(context: PluginContext): Promise<void> {
    context.logger.info('Activating CustomHeaderGenerator');

    // Read user configuration with defaults
    const company = (context.config.company as string) || 'YuleTech';
    const author = (context.config.author as string) || 'yuleASR Team';
    const license = (context.config.license as string) || 'Proprietary';

    context.logger.info(`Configuration: company="${company}", author="${author}"`);

    const generator: CodeGeneratorPlugin = {
      name: 'CopyrightHeader',
      description: 'Prepends a custom copyright header',
      supportedModules: ['*'], // Apply to all modules

      async generate(
        config: Record<string, unknown>,
        options: Record<string, unknown>,
      ): Promise<{ files: { path: string; content: string }[] }> {
        const year = new Date().getFullYear();
        const header = buildCopyrightHeader(company, author, license, year);

        // If the caller provided pre-generated content, wrap it.
        // Otherwise generate a minimal stub.
        const originalContent = (options.originalContent as string) ?? '';
        const moduleName = (config.module as string) || 'Unknown';

        let fileContent: string;
        if (originalContent) {
          fileContent = header + originalContent;
        } else {
          fileContent =
            header +
            `\
/* ==================================================================
 * ${moduleName} Configuration
 * ================================================================== */

#ifndef ${moduleName.toUpperCase()}_CFG_H
#define ${moduleName.toUpperCase()}_CFG_H

/* Module-specific configuration goes here */

#endif /* ${moduleName.toUpperCase()}_CFG_H */
`;
        }

        context.logger.info(
          `Generated header for module "${moduleName}" (${fileContent.length} bytes)`,
        );

        return {
          files: [
            {
              path: `${moduleName}_Cfg.h`,
              content: fileContent,
            },
          ],
        };
      },
    };

    context.registerCodeGenerator(generator);
    context.logger.info('CustomHeaderGenerator registered successfully');
  },

  async deactivate(): Promise<void> {
    console.info('[example-custom-header-generator] Plugin deactivated, resources cleaned up');
  },
};

export default customHeaderGenerator;
