/**
 * crossReferences 映射表（宏名版重写，2026-08-10）
 *
 * 背景：手写 generated/*.json 的 22 条 crossReferences 使用 ARXML 标准参数名
 * （如 WdgMExpectedAliveIndications），与宏名版 schema（extracted-cfgh，参数名即
 * yuleASR 手写头宏名，如 WDGM_CFG_MAX_SUPERVISED_ENTITIES）零对齐，不能直接合并。
 *
 * 本表按宏名版实际参数名重写规则，F1 提取器（extract-schemas-from-cfgh.ts）读取后
 * 注入 extracted-cfgh/*.json，使 110 模块配置链路具备跨模块依赖校验。
 *
 * 每条：sourceModule/sourceParam（宏名版）→ targetModule/targetParam（宏名版）
 * + relation（equals|less_than|greater_than|in_range|in_enum）+ severity + description。
 */
export interface CrossrefRule {
  sourceModule: string;
  sourceParam: string;
  targetModule: string;
  targetParam: string;
  relation: 'equals' | 'less_than' | 'greater_than' | 'in_range' | 'in_enum' | 'required';
  severity: 'error' | 'warning';
  description: string;
}

export const CROSSREF_RULES: CrossrefRule[] = [
  // ── 可直接落地（源/目标宏名版参数名均已验证存在）──
  {
    sourceModule: 'Can',
    sourceParam: 'CAN_BAUDRATE_500K',
    targetModule: 'CanTrcv',
    targetParam: 'CANTRCV_MAX_TRANSCEIVERS',
    relation: 'less_than',
    severity: 'warning',
    description: 'CAN 波特率配置应与收发器支持能力匹配',
  },
  {
    sourceModule: 'Fee',
    sourceParam: 'FEE_BLOCK_SIZE_512',
    targetModule: 'Fls',
    targetParam: 'FLS_MAX_READ_NORMAL_MODE',
    relation: 'less_than',
    severity: 'warning',
    description: 'Fee 块大小不应超过 Fls 支持的最大读取大小',
  },
  {
    sourceModule: 'NvM',
    sourceParam: 'NVM_NUM_OF_NVRAM_BLOCKS',
    targetModule: 'Fee',
    targetParam: 'FEE_NUM_BLOCKS',
    relation: 'less_than',
    severity: 'warning',
    description: 'NvM 块数不应超过 Fee 可配置块数',
  },
  {
    sourceModule: 'Crypto',
    sourceParam: 'CRYPTO_CFG_MAX_CHANNELS',
    targetModule: 'CryIf',
    targetParam: 'CRYIF_CFG_MAX_CHANNEL_COUNT',
    relation: 'less_than',
    severity: 'warning',
    description: 'Crypto 通道数不应超过 CryIf 可用通道数',
  },
  {
    sourceModule: 'Ea',
    sourceParam: 'EA_NUM_BLOCKS',
    targetModule: 'Eep',
    targetParam: 'EEP_SIZE',
    relation: 'less_than',
    severity: 'warning',
    description: 'Ea 块数应与 Eep 存储容量匹配',
  },

  // ── 参数名微调适配（源/目标宏名版实际参数名）──
  {
    sourceModule: 'LinIf',
    sourceParam: 'LINIF_MAX_CHANNELS',
    targetModule: 'Lin',
    targetParam: 'LIN_MAX_CHANNELS',
    relation: 'less_than',
    severity: 'warning',
    description: 'LinIf 通道数不应超过 Lin 可用通道数',
  },
  {
    sourceModule: 'WdgM',
    sourceParam: 'WDGM_CFG_MAX_SUPERVISED_ENTITIES',
    targetModule: 'WdgIf',
    targetParam: 'WDGIF_NUMBER_OF_DEVICES',
    relation: 'less_than',
    severity: 'warning',
    description: 'WdgM 监控实体数不应超过 WdgIf 设备数',
  },
  {
    sourceModule: 'Dem',
    sourceParam: 'DEM_NUM_DTCS',
    targetModule: 'Dcm',
    targetParam: 'DCM_NUM_PROTOCOLS',
    relation: 'in_range',
    severity: 'warning',
    description: 'Dem DTC 数量应与 Dcm 诊断协议容量匹配',
  },
  {
    sourceModule: 'Com',
    sourceParam: 'COM_MAX_IPDUS',
    targetModule: 'PduR',
    targetParam: 'PDUR_NUMBER_OF_ROUTING_PATHS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Com IPDU 数不应超过 PduR 路由路径数',
  },
  {
    sourceModule: 'Xcp',
    sourceParam: 'XCP_CAN_BAUDRATE',
    targetModule: 'Can',
    targetParam: 'CAN_BAUDRATE_500K',
    relation: 'less_than',
    severity: 'warning',
    description: 'Xcp CAN 波特率不应超过 Can 控制器波特率',
  },

  // ── 待 T3 补充的高频依赖（占位，验证后可扩充）──
  {
    sourceModule: 'CanIf',
    sourceParam: 'CANIF_NUM_TX_PDUS',
    targetModule: 'Can',
    targetParam: 'CAN_NUM_HOH',
    relation: 'less_than',
    severity: 'warning',
    description: 'CanIf 发送 PDU 数不应超过 Can 硬件对象数',
  },
  {
    sourceModule: 'NvM',
    sourceParam: 'NVM_NUM_OF_ROM_BLOCKS',
    targetModule: 'Ea',
    targetParam: 'EA_NUM_BLOCKS',
    relation: 'less_than',
    severity: 'warning',
    description: 'NvM ROM 块数不应超过 Ea 块数',
  },

  // ── T3 补充高频依赖（2026-08-10，参数名已验证存在）──
  {
    sourceModule: 'CanTp',
    sourceParam: 'CANTP_NUM_CHANNELS',
    targetModule: 'Can',
    targetParam: 'CAN_NUM_CONTROLLERS',
    relation: 'less_than',
    severity: 'warning',
    description: 'CanTp 通道数不应超过 Can 控制器数',
  },
  {
    sourceModule: 'CanSm',
    sourceParam: 'CANSM_NUM_NETWORKS',
    targetModule: 'Can',
    targetParam: 'CAN_NUM_CONTROLLERS',
    relation: 'less_than',
    severity: 'warning',
    description: 'CanSm 网络数不应超过 Can 控制器数',
  },
  {
    sourceModule: 'Eth',
    sourceParam: 'ETH_MAX_CONTROLLERS',
    targetModule: 'EthIf',
    targetParam: 'ETHIF_NUM_CONTROLLERS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Eth 控制器数应匹配 EthIf',
  },
  {
    sourceModule: 'Fls',
    sourceParam: 'FLS_MAX_READ_NORMAL_MODE',
    targetModule: 'Eep',
    targetParam: 'EEP_SIZE',
    relation: 'less_than',
    severity: 'warning',
    description: 'Fls 读取大小不应超过 Eep 容量',
  },
  {
    sourceModule: 'WdgM',
    sourceParam: 'WDGM_CFG_DEM_INTEGRATION',
    targetModule: 'Dem',
    targetParam: 'DEM_NUM_DTCS',
    relation: 'in_range',
    severity: 'warning',
    description: 'WdgM DEM 集成事件应在 Dem DTC 范围内',
  },
  {
    sourceModule: 'Gpt',
    sourceParam: 'GPT_NUM_CHANNELS',
    targetModule: 'Mcu',
    targetParam: 'MCU_NUM_CLOCK_CONFIGS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Gpt 通道数应匹配 Mcu 时钟配置',
  },
  {
    sourceModule: 'Com',
    sourceParam: 'COM_MAX_SIGNALS',
    targetModule: 'PduR',
    targetParam: 'PDUR_NUMBER_OF_ROUTING_PATHS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Com 信号数不应超过 PduR 路由路径数',
  },
  {
    sourceModule: 'Dcm',
    sourceParam: 'DCM_NUM_CONNECTIONS',
    targetModule: 'PduR',
    targetParam: 'PDUR_NUMBER_OF_ROUTING_PATHS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Dcm 连接数不应超过 PduR 路由路径数',
  },
  {
    sourceModule: 'CanIf',
    sourceParam: 'CANIF_NUM_RX_PDUS',
    targetModule: 'Can',
    targetParam: 'CAN_NUM_HOH',
    relation: 'less_than',
    severity: 'warning',
    description: 'CanIf 接收 PDU 数不应超过 Can 硬件对象数',
  },

  // ── T6 第二批高频依赖（2026-08-10，传输/存储/看门狗/诊断链，参数名已验证）──
  {
    sourceModule: 'CanTp',
    sourceParam: 'CANTP_NUM_CHANNELS',
    targetModule: 'PduR',
    targetParam: 'PDUR_NUMBER_OF_ROUTING_PATHS',
    relation: 'less_than',
    severity: 'warning',
    description: 'CanTp 通道数不应超过 PduR 路由路径数',
  },
  {
    sourceModule: 'PduR',
    sourceParam: 'PDUR_NUMBER_OF_ROUTING_PATHS',
    targetModule: 'CanIf',
    targetParam: 'CANIF_NUM_RX_PDUS',
    relation: 'less_than',
    severity: 'warning',
    description: 'PduR 路由路径数不应超过 CanIf 接收 PDU 数',
  },
  {
    sourceModule: 'NvM',
    sourceParam: 'NVM_NUM_OF_NVRAM_BLOCKS',
    targetModule: 'MemIf',
    targetParam: 'MEMIF_NUMBER_OF_DEVICES',
    relation: 'less_than',
    severity: 'warning',
    description: 'NvM 块数应匹配 MemIf 设备数',
  },
  {
    sourceModule: 'Fee',
    sourceParam: 'FEE_NUM_BLOCKS',
    targetModule: 'MemIf',
    targetParam: 'MEMIF_NUMBER_OF_DEVICES',
    relation: 'less_than',
    severity: 'warning',
    description: 'Fee 块数应匹配 MemIf 设备数',
  },
  {
    sourceModule: 'Ea',
    sourceParam: 'EA_NUM_BLOCKS',
    targetModule: 'MemIf',
    targetParam: 'MEMIF_NUMBER_OF_DEVICES',
    relation: 'less_than',
    severity: 'warning',
    description: 'Ea 块数应匹配 MemIf 设备数',
  },
  {
    sourceModule: 'FiM',
    sourceParam: 'FIM_NUM_FUNCTIONS',
    targetModule: 'Dem',
    targetParam: 'DEM_NUM_DTCS',
    relation: 'less_than',
    severity: 'warning',
    description: 'FiM 功能数不应超过 Dem DTC 数',
  },
  {
    sourceModule: 'WdgIf',
    sourceParam: 'WDGIF_NUMBER_OF_DEVICES',
    targetModule: 'WdgM',
    targetParam: 'WDGM_CFG_MAX_SUPERVISED_ENTITIES',
    relation: 'less_than',
    severity: 'warning',
    description: 'WdgIf 设备数不应超过 WdgM 监督实体数',
  },
  {
    sourceModule: 'Dcm',
    sourceParam: 'DCM_NUM_CONNECTIONS',
    targetModule: 'CanTp',
    targetParam: 'CANTP_NUM_CHANNELS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Dcm 连接数不应超过 CanTp 通道数',
  },
  {
    sourceModule: 'EthIf',
    sourceParam: 'ETHIF_NUM_FRAME_OWNERS',
    targetModule: 'Eth',
    targetParam: 'ETH_MAX_CONTROLLERS',
    relation: 'less_than',
    severity: 'warning',
    description: 'EthIf 帧属主数不应超过 Eth 控制器数',
  },
  {
    sourceModule: 'LinIf',
    sourceParam: 'LINIF_MAX_CHANNELS',
    targetModule: 'Lin',
    targetParam: 'LIN_MAX_CHANNELS',
    relation: 'less_than',
    severity: 'warning',
    description: 'LinIf 通道数不应超过 Lin 通道数',
  },

  // ── T7 第三批高频依赖（2026-08-10，通信/诊断/存储/时钟链，参数名已验证）──
  {
    sourceModule: 'Com',
    sourceParam: 'COM_MAX_SIGNALS',
    targetModule: 'CanIf',
    targetParam: 'CANIF_NUM_RX_PDUS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Com 信号数不应超过 CanIf 接收 PDU 数',
  },
  {
    sourceModule: 'CanIf',
    sourceParam: 'CANIF_NUM_TX_PDUS',
    targetModule: 'CanTp',
    targetParam: 'CANTP_NUM_CHANNELS',
    relation: 'less_than',
    severity: 'warning',
    description: 'CanIf 发送 PDU 数不应超过 CanTp 通道数',
  },
  {
    sourceModule: 'PduR',
    sourceParam: 'PDUR_NUMBER_OF_ROUTING_PATHS',
    targetModule: 'Dcm',
    targetParam: 'DCM_NUM_CONNECTIONS',
    relation: 'less_than',
    severity: 'warning',
    description: 'PduR 路由路径数不应超过 Dcm 连接数',
  },
  {
    sourceModule: 'NvM',
    sourceParam: 'NVM_NUM_OF_NVRAM_BLOCKS',
    targetModule: 'Fee',
    targetParam: 'FEE_NUM_BLOCKS',
    relation: 'less_than',
    severity: 'warning',
    description: 'NvM 块数不应超过 Fee 块数',
  },
  {
    sourceModule: 'Crypto',
    sourceParam: 'CRYPTO_CFG_MAX_CHANNELS',
    targetModule: 'Csm',
    targetParam: 'CSM_CFG_MAX_CONCURRENT_JOBS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Crypto 通道数不应超过 Csm 并发任务数',
  },
  {
    sourceModule: 'Csm',
    sourceParam: 'CSM_CFG_MAX_CONCURRENT_JOBS',
    targetModule: 'Crypto',
    targetParam: 'CRYPTO_CFG_MAX_CHANNELS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Csm 并发任务数不应超过 Crypto 通道数',
  },
  {
    sourceModule: 'WdgM',
    sourceParam: 'WDGM_CFG_MAX_SUPERVISED_ENTITIES',
    targetModule: 'Dem',
    targetParam: 'DEM_NUM_DTCS',
    relation: 'less_than',
    severity: 'warning',
    description: 'WdgM 监督实体数不应超过 Dem DTC 数',
  },
  {
    sourceModule: 'Mcu',
    sourceParam: 'MCU_NUM_CLOCK_CONFIGS',
    targetModule: 'Gpt',
    targetParam: 'GPT_NUM_CHANNELS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Mcu 时钟配置数不应少于 Gpt 通道数',
  },
  {
    sourceModule: 'Lin',
    sourceParam: 'LIN_MAX_CHANNELS',
    targetModule: 'LinIf',
    targetParam: 'LINIF_MAX_CHANNELS',
    relation: 'equals',
    severity: 'warning',
    description: 'Lin 通道数应等于 LinIf 通道数',
  },
  {
    sourceModule: 'Can',
    sourceParam: 'CAN_NUM_CONTROLLERS',
    targetModule: 'CanIf',
    targetParam: 'CANIF_NUM_TX_PDUS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Can 控制器数不应超过 CanIf 发送 PDU 数',
  },

  // ── T8 第四批高频依赖（2026-08-10，IO/驱动层，参数名已验证）──
  {
    sourceModule: 'Dio',
    sourceParam: 'DIO_NUM_PORTS',
    targetModule: 'Port',
    targetParam: 'PORT_NUM_PORTS',
    relation: 'equals',
    severity: 'warning',
    description: 'Dio 端口数应等于 Port 端口数',
  },
  {
    sourceModule: 'Dio',
    sourceParam: 'DIO_NUM_CHANNELS_PER_PORT',
    targetModule: 'Port',
    targetParam: 'PORT_NUM_PINS_PER_PORT',
    relation: 'equals',
    severity: 'warning',
    description: 'Dio 每端口通道数应等于 Port 每端口引脚数',
  },
  {
    sourceModule: 'Adc',
    sourceParam: 'ADC_NUM_GROUPS',
    targetModule: 'Port',
    targetParam: 'PORT_TOTAL_NUM_PINS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Adc 组数不应超过 Port 引脚数',
  },
  {
    sourceModule: 'Pwm',
    sourceParam: 'PWM_NUM_CHANNELS',
    targetModule: 'Port',
    targetParam: 'PORT_TOTAL_NUM_PINS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Pwm 通道数不应超过 Port 引脚数',
  },
  {
    sourceModule: 'Icu',
    sourceParam: 'ICU_NUM_CHANNELS',
    targetModule: 'Port',
    targetParam: 'PORT_TOTAL_NUM_PINS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Icu 通道数不应超过 Port 引脚数',
  },
  {
    sourceModule: 'Spi',
    sourceParam: 'SPI_CHANNEL_COUNT',
    targetModule: 'Port',
    targetParam: 'PORT_TOTAL_NUM_PINS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Spi 通道数不应超过 Port 引脚数',
  },
  {
    sourceModule: 'Uart',
    sourceParam: 'UART_CHANNEL_COUNT',
    targetModule: 'Port',
    targetParam: 'PORT_TOTAL_NUM_PINS',
    relation: 'less_than',
    severity: 'warning',
    description: 'Uart 通道数不应超过 Port 引脚数',
  },
  {
    sourceModule: 'NvM',
    sourceParam: 'NVM_NUM_OF_NVRAM_BLOCKS',
    targetModule: 'Mcu',
    targetParam: 'MCU_NUM_RAM_SECTIONS',
    relation: 'less_than',
    severity: 'warning',
    description: 'NvM 块数不应超过 Mcu RAM 段数',
  },

  // ── T10 依赖必须存在（required，2026-08-10 老板钦定）──
  // 源模块配置后，目标模块/参数必须存在；缺失 → 报错（如 Can 依赖时钟）
  {
    sourceModule: 'Can',
    sourceParam: 'CAN_NUM_CONTROLLERS',
    targetModule: 'Mcu',
    targetParam: 'MCU_SYSTEM_CLOCK_HZ',
    relation: 'required',
    severity: 'error',
    description: 'Can 模块依赖 Mcu 系统时钟，时钟必须配置',
  },
  {
    sourceModule: 'Can',
    sourceParam: 'CAN_BAUDRATE_500K',
    targetModule: 'Mcu',
    targetParam: 'MCU_SYSTEM_CLOCK_HZ',
    relation: 'required',
    severity: 'error',
    description: 'Can 波特率依赖 Mcu 系统时钟，时钟必须配置',
  },
  {
    sourceModule: 'Gpt',
    sourceParam: 'GPT_NUM_CHANNELS',
    targetModule: 'Mcu',
    targetParam: 'MCU_SYSTEM_CLOCK_HZ',
    relation: 'required',
    severity: 'error',
    description: 'Gpt 模块依赖 Mcu 系统时钟，时钟必须配置',
  },
  {
    sourceModule: 'CanTp',
    sourceParam: 'CANTP_NUM_CHANNELS',
    targetModule: 'Can',
    targetParam: 'CAN_NUM_CONTROLLERS',
    relation: 'required',
    severity: 'error',
    description: 'CanTp 依赖 Can 控制器，Can 必须配置',
  },
  {
    sourceModule: 'CanIf',
    sourceParam: 'CANIF_NUM_RX_PDUS',
    targetModule: 'Can',
    targetParam: 'CAN_NUM_CONTROLLERS',
    relation: 'required',
    severity: 'error',
    description: 'CanIf 依赖 Can 控制器，Can 必须配置',
  },
  {
    sourceModule: 'CanSm',
    sourceParam: 'CANSM_NUM_NETWORKS',
    targetModule: 'Can',
    targetParam: 'CAN_NUM_CONTROLLERS',
    relation: 'required',
    severity: 'error',
    description: 'CanSm 依赖 Can 控制器，Can 必须配置',
  },
  {
    sourceModule: 'EthIf',
    sourceParam: 'ETHIF_NUM_CONTROLLERS',
    targetModule: 'Eth',
    targetParam: 'ETH_MAX_CONTROLLERS',
    relation: 'required',
    severity: 'error',
    description: 'EthIf 依赖 Eth 控制器，Eth 必须配置',
  },
  {
    sourceModule: 'LinIf',
    sourceParam: 'LINIF_MAX_CHANNELS',
    targetModule: 'Lin',
    targetParam: 'LIN_MAX_CHANNELS',
    relation: 'required',
    severity: 'error',
    description: 'LinIf 依赖 Lin 通道，Lin 必须配置',
  },
  {
    sourceModule: 'NvM',
    sourceParam: 'NVM_NUM_OF_NVRAM_BLOCKS',
    targetModule: 'MemIf',
    targetParam: 'MEMIF_NUMBER_OF_DEVICES',
    relation: 'required',
    severity: 'error',
    description: 'NvM 依赖 MemIf 设备，MemIf 必须配置',
  },
  {
    sourceModule: 'Fee',
    sourceParam: 'FEE_NUM_BLOCKS',
    targetModule: 'MemIf',
    targetParam: 'MEMIF_NUMBER_OF_DEVICES',
    relation: 'required',
    severity: 'error',
    description: 'Fee 依赖 MemIf 设备，MemIf 必须配置',
  },
  {
    sourceModule: 'Crypto',
    sourceParam: 'CRYPTO_CFG_MAX_CHANNELS',
    targetModule: 'Csm',
    targetParam: 'CSM_CFG_MAX_CONCURRENT_JOBS',
    relation: 'required',
    severity: 'error',
    description: 'Crypto 依赖 Csm 并发任务，Csm 必须配置',
  },
  {
    sourceModule: 'Dcm',
    sourceParam: 'DCM_NUM_CONNECTIONS',
    targetModule: 'PduR',
    targetParam: 'PDUR_NUMBER_OF_ROUTING_PATHS',
    relation: 'required',
    severity: 'error',
    description: 'Dcm 依赖 PduR 路由路径，PduR 必须配置',
  },
];

/**
 * MODULE_DEPENDENCY_RULES — 模块级依赖（2026-08-10 统一管理）
 *
 * 背景：原先 35 条模块依赖硬编码在 yuleasr-validator.ts 的 dependencyRules 表，
 * 本次迁移到数据文件统一管理（与 crossReferences 同源），由 F1 提取器注入
 * extracted-cfgh/*.json 的 dependencies 字段，yuleasr-validator 改为从 schema 读取。
 *
 * 语义：sourceModule 被配置时，目标模块必须存在（required=error）或建议存在
 * （required=false → warning）；paramCheck 支持模块存在时的进一步参数级校验。
 */
export interface ModuleDependencyRule {
  sourceModule: string;
  targetModule: string;
  required: boolean;
  message: string;
  paramCheck?: {
    type: 'container_not_empty' | 'value_gt' | 'value_equals';
    container?: string;
    param?: string;
    expected?: unknown;
  };
}

export const MODULE_DEPENDENCY_RULES: ModuleDependencyRule[] = [
  {
    sourceModule: 'CanIf',
    targetModule: 'Can',
    required: true,
    message: 'CanIf requires Can driver',
  },
  {
    sourceModule: 'CanIf',
    targetModule: 'Can',
    required: false,
    message: 'CanIf requires at least one CAN controller configured',
    paramCheck: { type: 'container_not_empty', container: 'CanController' },
  },
  { sourceModule: 'CanNm', targetModule: 'CanIf', required: true, message: 'CanNm requires CanIf' },
  { sourceModule: 'CanNm', targetModule: 'Nm', required: true, message: 'CanNm requires Nm' },
  { sourceModule: 'CanSm', targetModule: 'CanIf', required: true, message: 'CanSM requires CanIf' },
  {
    sourceModule: 'CanSm',
    targetModule: 'ComM',
    required: false,
    message: 'CanSM should have ComM',
  },
  { sourceModule: 'CanTp', targetModule: 'CanIf', required: true, message: 'CanTp requires CanIf' },
  { sourceModule: 'CanTp', targetModule: 'PduR', required: true, message: 'CanTp requires PduR' },
  {
    sourceModule: 'CanTrcv',
    targetModule: 'Can',
    required: false,
    message: 'CanTrcv should have Can',
  },
  { sourceModule: 'Com', targetModule: 'PduR', required: true, message: 'Com requires PduR' },
  { sourceModule: 'ComM', targetModule: 'Com', required: true, message: 'ComM requires Com' },
  { sourceModule: 'ComM', targetModule: 'Nm', required: false, message: 'ComM should have Nm' },
  { sourceModule: 'Dcm', targetModule: 'Com', required: true, message: 'Dcm requires Com' },
  { sourceModule: 'Dcm', targetModule: 'PduR', required: true, message: 'Dcm requires PduR' },
  { sourceModule: 'Dcm', targetModule: 'Dem', required: false, message: 'Dcm should have Dem' },
  { sourceModule: 'Dem', targetModule: 'Dcm', required: true, message: 'Dem requires Dcm' },
  { sourceModule: 'Dem', targetModule: 'NvM', required: false, message: 'Dem should have NvM' },
  { sourceModule: 'Dio', targetModule: 'Port', required: true, message: 'Dio requires Port' },
  { sourceModule: 'Dio', targetModule: 'Mcu', required: false, message: 'Dio should have Mcu' },
  { sourceModule: 'EcuM', targetModule: 'Mcu', required: true, message: 'EcuM requires Mcu' },
  { sourceModule: 'Fee', targetModule: 'Fls', required: true, message: 'Fee requires Fls' },
  { sourceModule: 'Fee', targetModule: 'MemIf', required: true, message: 'Fee requires MemIf' },
  { sourceModule: 'Fls', targetModule: 'Mcu', required: false, message: 'Fls should have Mcu' },
  { sourceModule: 'Gpt', targetModule: 'Mcu', required: false, message: 'Gpt should have Mcu' },
  { sourceModule: 'Icu', targetModule: 'Mcu', required: false, message: 'Icu should have Mcu' },
  { sourceModule: 'Mcl', targetModule: 'Mcu', required: false, message: 'Mcl should have Mcu' },
  {
    sourceModule: 'MemIf',
    targetModule: 'Fee',
    required: true,
    message: 'MemIf requires Fee or Ea',
  },
  { sourceModule: 'Nm', targetModule: 'ComM', required: true, message: 'Nm requires ComM' },
  { sourceModule: 'NvM', targetModule: 'MemIf', required: true, message: 'NvM requires MemIf' },
  { sourceModule: 'Os', targetModule: 'EcuM', required: false, message: 'Os should have EcuM' },
  { sourceModule: 'PduR', targetModule: 'CanIf', required: true, message: 'PduR requires CanIf' },
  { sourceModule: 'Rte', targetModule: 'Os', required: true, message: 'Rte requires Os' },
  { sourceModule: 'Rte', targetModule: 'Com', required: false, message: 'Rte should have Com' },
  { sourceModule: 'Spi', targetModule: 'Mcu', required: false, message: 'Spi should have Mcu' },
  { sourceModule: 'Adc', targetModule: 'Mcu', required: false, message: 'Adc should have Mcu' },
  { sourceModule: 'Port', targetModule: 'Mcu', required: false, message: 'Port should have Mcu' },
];
