/**
 * @file    Ecuc_Spi_Cfg.h
 * @brief   AUTOSAR Spi - SPI Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Spi module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Spi BSW module implementation.
 *
 * @module     Spi
 * @moduleId   122
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.598Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_SPI_CFG_H
#define ECUC_SPI_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[AUTOSAR version information]============================*/
/**
 * @brief Spi Software Version
 */
#define SPI_SW_MAJOR_VERSION          ((uint8)4U)
#define SPI_SW_MINOR_VERSION          ((uint8)4U)
#define SPI_SW_PATCH_VERSION          ((uint8)0U)

/**
 * @brief AUTOSAR Release Version
 */
#define SPI_AR_RELEASE_MAJOR_VERSION  ((uint8)4U)
#define SPI_AR_RELEASE_MINOR_VERSION  ((uint8)4U)
#define SPI_AR_RELEASE_REVISION_VERSION ((uint8)0U)

/**
 * @brief Module ID and Vendor ID
 */
#define SPI_MODULE_ID                 ((uint16)0x007A)
#define SPI_VENDOR_ID                 ((uint16)0x1234)

/**
 * @brief Development error detection switch
 */
#define SPI_DEV_ERROR_DETECT          STD_OFF

/*==================[vendor identification]==================================*/
/**
 * @brief YuleTech vendor information
 */
#define YULETECH_VENDOR_ID              ((uint16)0x1234)

/*==================[parameter macros]======================================*/
#define SPI_SPIDEVERRORDETECT    STD_ON
#define SPI_SPINUMCHANNELS    ((uint16)8U)
#define SPI_SPINUMJOBS    ((uint16)8U)
#define SPI_SPINUMSEQUENCES    ((uint16)4U)
/** @brief Number of SpiChannel instances */
#define SPI_SPICHANNEL_COUNT    1U
/** @brief Number of SpiHwUnit instances */
#define SPI_SPIHWUNIT_COUNT    1U

/*==================[type definitions]======================================*/
/** @brief SPI Channel container type */
typedef struct {
} Spi_SpiChannelType;

/** @brief SPI HW Unit container type */
typedef struct {
} Spi_SpiHwUnitType;

/** @brief Spi configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean spiDevErrorDetect;
    uint32 spiNumChannels;
    uint32 spiNumJobs;
    uint32 spiNumSequences;
    const Spi_SpiChannelType* SpiChannel;
    const Spi_SpiHwUnitType* SpiHwUnit;
} Spi_ConfigSetType;

/** @brief Spi configuration type */
typedef struct {
    const Spi_ConfigSetType* configSet;
} Spi_ConfigType;

/*==================[external data declarations]============================*/
#define SPI_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Spi_ConfigSetType Spi_ConfigSet;
/** @brief External configuration structure */
extern const Spi_ConfigType Spi_Config;

/** @brief SpiChannel container instances */
extern const Spi_SpiChannelType SpiChannel_Instances[1];
/** @brief SpiHwUnit container instances */
extern const Spi_SpiHwUnitType SpiHwUnit_Instances[1];

#define SPI_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[function declarations]=================================*/
/**
 * @brief Initialize the Spi module
 *
 * @param [in] ConfigPtr  Pointer to the Spi configuration set
 *
 * @pre  The module shall be uninitialized
 *
 * @post The Spi module is fully initialized and operational
 *
 * @return Std_ReturnType: E_OK if initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Spi_Init(const Spi_ConfigType* ConfigPtr);

/**
 * @brief De-initialize the Spi module
 *
 * @pre  The Spi module shall be initialized
 *
 * @post The Spi module is de-initialized and no longer operational
 *
 * @return Std_ReturnType: E_OK if de-initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Spi_DeInit(void);

/**
 * @brief Spi main function - scheduled cyclic processing
 *
 * @pre  The Spi module shall be initialized
 *
 * @post All pending Spi processing is completed for this cycle
 *
 * @return void
 */
void Spi_MainFunction(void);

/**
 * @brief Get the Spi module version information
 *
 * @param [out] versioninfo  Pointer to the version information structure to be filled
 *
 * @pre  versioninfo shall not be NULL_PTR
 *
 * @post The version structure contains the Spi module's vendor, module, and software version IDs
 *
 * @return void
 */
void Spi_GetVersionInfo(Std_VersionInfoType* versioninfo);

/**
 * @brief Check if the Spi module is initialized
 *
 * @return boolean: TRUE if the module is initialized, FALSE otherwise
 */
boolean Spi_IsInitialized(void);

#endif /* ECUC_SPI_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page spi_cfg_page Spi Configuration
 * @brief This page documents the Spi module configuration parameters.
 *
 * @section spi_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Spi AUTOSAR BSW module.
 *
 * @section spi_cfg_usage Usage
 * Include this file in your Spi module implementation to access
 * the configured parameters.
 *
 * @section spi_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
