/**
 * @file    Ecuc_Spi.c
 * @brief   AUTOSAR Spi - SPI Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Spi module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Spi BSW module implementation.
 *
 * @module     Spi
 * @moduleId   122
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.104Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Spi_Cfg.h"

/*==================[module information]====================================*/
/**
 * @brief Spi module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   122
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
__attribute__((unused)) static const Std_VersionInfoType Spi_VersionInfo = {
    .vendorID = SPI_VENDOR_ID,
    .moduleID = SPI_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Spi module initialization state */
__attribute__((unused)) static boolean Spi_Initialized = FALSE;

/*==================[configuration data]==================================*/
#define SPI_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief SpiChannel instance 0 */
static const Spi_SpiChannelType SpiChannel_Instance_0 = {
};

/** @brief SpiChannel instance 1 */
static const Spi_SpiChannelType SpiChannel_Instance_1 = {
};

/** @brief SpiChannel instance array */
const Spi_SpiChannelType SpiChannel_Instances[2] = {
    SpiChannel_Instance_0,
    SpiChannel_Instance_1,
};

/** @brief SpiHwUnit instance 0 */
static const Spi_SpiHwUnitType SpiHwUnit_Instance_0 = {
};

/** @brief SpiHwUnit instance 1 */
static const Spi_SpiHwUnitType SpiHwUnit_Instance_1 = {
};

/** @brief SpiHwUnit instance array */
const Spi_SpiHwUnitType SpiHwUnit_Instances[2] = {
    SpiHwUnit_Instance_0,
    SpiHwUnit_Instance_1,
};

/** @brief Spi configuration set structure */
const Spi_ConfigSetType Spi_ConfigSet = {
    .moduleId = SPI_MODULE_ID,
    .versionInfo = {4, 4, 0},
    .instanceCount = 2,
    .spiDevErrorDetect = STD_ON,
    .spiNumChannels = ((uint16)8U),
    .spiNumJobs = ((uint16)8U),
    .spiNumSequences = ((uint16)4U),
    .SpiChannel = SpiChannel_Instances,
    .SpiHwUnit = SpiHwUnit_Instances,
};


#define SPI_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Spi.c
 */
