/**
 * @file    Ecuc_Spi_Cfg.h
 * @brief   AUTOSAR Spi - SPI Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Spi module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Spi BSW module implementation.
 *
 * @module     Spi
 * @moduleId   122
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.104Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_SPI_CFG_H
#define ECUC_SPI_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[module identification]==================================*/
/** @brief Spi module identification (ECUC config data) */
#ifndef SPI_MODULE_ID
#define SPI_MODULE_ID            ((uint16)0x007A)
#endif /* SPI_MODULE_ID */
#ifndef SPI_VENDOR_ID
#define SPI_VENDOR_ID            ((uint16)0x1234)
#endif /* SPI_VENDOR_ID */

/*==================[parameter macros]======================================*/
#define SPI_SPIDEVERRORDETECT    STD_ON
#ifndef SPI_DEV_ERROR_DETECT
#define SPI_DEV_ERROR_DETECT    STD_ON
#endif /* SPI_DEV_ERROR_DETECT */
#define SPI_SPINUMCHANNELS    ((uint16)8U)
#define SPI_SPINUMJOBS    ((uint16)8U)
#define SPI_SPINUMSEQUENCES    ((uint16)4U)
/** @brief Number of SpiChannel instances */
#define SPI_SPICHANNEL_COUNT    2U
/** @brief Number of SpiHwUnit instances */
#define SPI_SPIHWUNIT_COUNT    2U

/*==================[type definitions]======================================*/
/** @brief SPI Channel container type */
typedef struct {
} Spi_SpiChannelType;

/** @brief SPI HW Unit container type */
typedef struct {
} Spi_SpiHwUnitType;

/** @brief Spi configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean spiDevErrorDetect;
    uint32 spiNumChannels;
    uint32 spiNumJobs;
    uint32 spiNumSequences;
    const Spi_SpiChannelType* SpiChannel;
    const Spi_SpiHwUnitType* SpiHwUnit;
} Spi_ConfigSetType;

/*==================[external data declarations]============================*/
#define SPI_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Spi_ConfigSetType Spi_ConfigSet;

/** @brief SpiChannel container instances */
extern const Spi_SpiChannelType SpiChannel_Instances[2];
/** @brief SpiHwUnit container instances */
extern const Spi_SpiHwUnitType SpiHwUnit_Instances[2];

#define SPI_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif /* ECUC_SPI_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page spi_cfg_page Spi Configuration
 * @brief This page documents the Spi module configuration parameters.
 *
 * @section spi_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Spi AUTOSAR BSW module.
 *
 * @section spi_cfg_usage Usage
 * Include this file in your Spi module implementation to access
 * the configured parameters.
 *
 * @section spi_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
