/**
 * @file    Ecuc_Port.c
 * @brief   AUTOSAR Port - PORT Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Port module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Port BSW module implementation.
 *
 * @module     Port
 * @moduleId   42
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.596Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Port_Cfg.h"

/*==================[module information]====================================*/
/**
 * @brief Port module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   42
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
static const Std_VersionInfoType Port_VersionInfo = {
    .vendorID = PORT_VENDOR_ID,
    .moduleID = PORT_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Port module initialization state */
static boolean Port_Initialized = FALSE;

/*==================[configuration data]==================================*/
#define PORT_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief PortPin instance 0 */
static const Port_PortPinType PortPin_Instance_0 = {
};

/** @brief PortPin instance array */
const Port_PortPinType PortPin_Instances[1] = {
    PortPin_Instance_0,
};

/** @brief Port configuration set structure */
const Port_ConfigSetType Port_ConfigSet = {
    .moduleId = PORT_MODULE_ID,
    .versionInfo = {4, 4, 0},
    .instanceCount = 1,
    .portDevErrorDetect = STD_ON,
    .portPinCount = ((uint16)8U),
    .PortPin = PortPin_Instances,
};

/** @brief Port configuration type */
const Port_ConfigType Port_Config = {
    .configSet = &Port_ConfigSet,
};


#define PORT_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Port.c
 */
