/**
 * @file    Ecuc_Port.c
 * @brief   AUTOSAR Port - PORT Driver ECU Configuration Source
 * @details This file contains the AUTOSAR 4.4 compliant Port module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Port BSW module implementation.
 *
 * @module     Port
 * @moduleId   42
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.101Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Port_Cfg.h"
#include "Port.h"

/*==================[module information]====================================*/
/**
 * @brief Port module version information
 * @details Static version information structure following AUTOSAR Std_VersionInfoType
 * 
 * Vendor ID:   0x1234 (YuleTech)
 * Module ID:   42
 * SW Version:  4.4.0
 * AR Version:  4.4.0
 */
__attribute__((unused)) static const Std_VersionInfoType Port_VersionInfo = {
    .vendorID = PORT_VENDOR_ID,
    .moduleID = PORT_MODULE_ID,
    .sw_major_version = 4,
    .sw_minor_version = 4,
    .sw_patch_version = 0
};

/** @brief Port module initialization state */
__attribute__((unused)) static boolean Port_Initialized = FALSE;

#define PORT_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[yuleASR flat config - Port_Config]============*/
/**
 * @brief yuleASR flat configuration - Port_Config
 * @details
 * This section directly defines the Port_Config symbol expected by
 * yuleASR's Port.h driver header. The data is generated flat,
 * without the AUTOSAR ConfigSet nesting layer.
 *
 * The Port.h header is included at the top of this file.
 */

static const Port_PinConfigType PortPin_0 = {
    .Pin = ((uint16)0U),
    .Direction = (Port_PinDirectionType)1,
    .Mode = ((uint16)0U),
    .DirectionChangeable = STD_OFF,
    .ModeChangeable = STD_OFF,
    .InitialLevel = (Port_PinLevelType)0,
    .PullUpEnable = STD_OFF,
    .PullDownEnable = STD_OFF,
};

static const Port_PinConfigType PortPin_1 = {
    .Pin = ((uint16)1U),
    .Direction = (Port_PinDirectionType)0,
    .Mode = ((uint16)0U),
    .DirectionChangeable = STD_OFF,
    .ModeChangeable = STD_OFF,
    .InitialLevel = (Port_PinLevelType)0,
    .PullUpEnable = STD_OFF,
    .PullDownEnable = STD_OFF,
};

static const Port_PinConfigType Port_PinConfigs[2] = {
    PortPin_0,
    PortPin_1,
};

/** @brief yuleASR Port_Config instance */
const Port_ConfigType Port_Config = {
    .NumPins = ((uint16)8U),
    .PinConfigs = Port_PinConfigs,
};


#define PORT_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/*==================[constants]=============================================*/

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Port.c
 */
