/**
 * @file    Ecuc_Port_PBcfg.c
 * @brief   AUTOSAR Port - PORT Driver Post-Build Configuration
 * @details This file contains the AUTOSAR 4.4 compliant Port module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Port BSW module implementation.
 *
 * @module     Port
 * @moduleId   42
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.596Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[includes]==============================================*/
#include "Ecuc_Port_Cfg.h"

/*==================[post-build configuration]==============================*/
/**
 * @brief Port Post-Build Configuration Data
 * @details This file contains configuration data that can be modified
 *          after the build process. Post-Build configuration allows
 *          parameter changes without recompilation.
 */
/* Post-Build configurable parameters */
Port_ConfigSetType Port_PostBuildConfig = {
    .portDevErrorDetect = STD_ON,
    .portPinCount = ((uint16)8U),
};

/*==================[end of file]===========================================*/
/**
 * End of Ecuc_Port_PBcfg.c
 */
