/**
 * @file    Ecuc_Port_Cfg.h
 * @brief   AUTOSAR Port - PORT Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Port module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Port BSW module implementation.
 *
 * @module     Port
 * @moduleId   42
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-08-21T11:57:59.101Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_PORT_CFG_H
#define ECUC_PORT_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[module identification]==================================*/
/** @brief Port module identification (ECUC config data) */
#ifndef PORT_MODULE_ID
#define PORT_MODULE_ID            ((uint16)0x002A)
#endif /* PORT_MODULE_ID */
#ifndef PORT_VENDOR_ID
#define PORT_VENDOR_ID            ((uint16)0x1234)
#endif /* PORT_VENDOR_ID */

/*==================[parameter macros]======================================*/
#define PORT_PORTDEVERRORDETECT    STD_ON
#ifndef PORT_DEV_ERROR_DETECT
#define PORT_DEV_ERROR_DETECT    STD_ON
#endif /* PORT_DEV_ERROR_DETECT */
#define PORT_PORTPINCOUNT    ((uint16)8U)
/** @brief Number of PortPin instances */
#define PORT_PORTPIN_COUNT    2U

/*==================[type definitions]======================================*/
/*==================[external data declarations]============================*/
#define PORT_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

#define PORT_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif /* ECUC_PORT_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page port_cfg_page Port Configuration
 * @brief This page documents the Port module configuration parameters.
 *
 * @section port_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Port AUTOSAR BSW module.
 *
 * @section port_cfg_usage Usage
 * Include this file in your Port module implementation to access
 * the configured parameters.
 *
 * @section port_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
