/**
 * @file    Ecuc_Port_Cfg.h
 * @brief   AUTOSAR Port - PORT Driver Configuration Header
 * @details This file contains the AUTOSAR 4.4 compliant Port module
 *          configuration data structures, type definitions, and function declarations.
 *          It is part of the Port BSW module implementation.
 *
 * @module     Port
 * @moduleId   42
 * @vendorId   0x1234
 * @copyright  Copyright (c) 2026 YuleTech. All rights reserved.
 *
 * AUTOSAR Version Information:
 * @arVersion   4.4.0
 * @swVersion   1.0.0
 *
 * @note  This file is auto-generated by yuleASR Configurator.
 *        DO NOT EDIT THIS FILE MANUALLY.
 * @date  2026-07-23T17:07:55.596Z
 */
/*==============================================================================
 *                                           C O N F I D E N T I A L
 *==============================================================================
 * This file contains confidential and proprietary information of YuleTech.
 * Unauthorized copying or distribution of this file is prohibited.
 *============================================================================*/
/*==================[preprocessor guards]====================================*/
#ifndef ECUC_PORT_CFG_H
#define ECUC_PORT_CFG_H

/*==================[includes]==============================================*/
#include "Std_Types.h"
#include "Ecuc.h"

/*==================[AUTOSAR version information]============================*/
/**
 * @brief Port Software Version
 */
#define PORT_SW_MAJOR_VERSION          ((uint8)4U)
#define PORT_SW_MINOR_VERSION          ((uint8)4U)
#define PORT_SW_PATCH_VERSION          ((uint8)0U)

/**
 * @brief AUTOSAR Release Version
 */
#define PORT_AR_RELEASE_MAJOR_VERSION  ((uint8)4U)
#define PORT_AR_RELEASE_MINOR_VERSION  ((uint8)4U)
#define PORT_AR_RELEASE_REVISION_VERSION ((uint8)0U)

/**
 * @brief Module ID and Vendor ID
 */
#define PORT_MODULE_ID                 ((uint16)0x002A)
#define PORT_VENDOR_ID                 ((uint16)0x1234)

/**
 * @brief Development error detection switch
 */
#define PORT_DEV_ERROR_DETECT          STD_OFF

/*==================[vendor identification]==================================*/
/**
 * @brief YuleTech vendor information
 */
#define YULETECH_VENDOR_ID              ((uint16)0x1234)

/*==================[parameter macros]======================================*/
#define PORT_PORTDEVERRORDETECT    STD_ON
#define PORT_PORTPINCOUNT    ((uint16)8U)
/** @brief Number of PortPin instances */
#define PORT_PORTPIN_COUNT    1U

/*==================[type definitions]======================================*/
/** @brief Port Pin container type */
typedef struct {
} Port_PortPinType;

/** @brief Port configuration set type */
typedef struct {
    uint16 moduleId;
    uint8 versionInfo[3];
    uint8 instanceCount;
    boolean portDevErrorDetect;
    uint32 portPinCount;
    const Port_PortPinType* PortPin;
} Port_ConfigSetType;

/** @brief Port configuration type */
typedef struct {
    const Port_ConfigSetType* configSet;
} Port_ConfigType;

/*==================[external data declarations]============================*/
#define PORT_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
/** @brief External configuration set structure */
extern const Port_ConfigSetType Port_ConfigSet;
/** @brief External configuration structure */
extern const Port_ConfigType Port_Config;

/** @brief PortPin container instances */
extern const Port_PortPinType PortPin_Instances[1];

#define PORT_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[function declarations]=================================*/
/**
 * @brief Initialize the Port module
 *
 * @param [in] ConfigPtr  Pointer to the Port configuration set
 *
 * @pre  The module shall be uninitialized
 *
 * @post The Port module is fully initialized and operational
 *
 * @return Std_ReturnType: E_OK if initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Port_Init(const Port_ConfigType* ConfigPtr);

/**
 * @brief De-initialize the Port module
 *
 * @pre  The Port module shall be initialized
 *
 * @post The Port module is de-initialized and no longer operational
 *
 * @return Std_ReturnType: E_OK if de-initialization succeeded, E_NOT_OK otherwise
 */
Std_ReturnType Port_DeInit(void);

/**
 * @brief Port main function - scheduled cyclic processing
 *
 * @pre  The Port module shall be initialized
 *
 * @post All pending Port processing is completed for this cycle
 *
 * @return void
 */
void Port_MainFunction(void);

/**
 * @brief Get the Port module version information
 *
 * @param [out] versioninfo  Pointer to the version information structure to be filled
 *
 * @pre  versioninfo shall not be NULL_PTR
 *
 * @post The version structure contains the Port module's vendor, module, and software version IDs
 *
 * @return void
 */
void Port_GetVersionInfo(Std_VersionInfoType* versioninfo);

/**
 * @brief Check if the Port module is initialized
 *
 * @return boolean: TRUE if the module is initialized, FALSE otherwise
 */
boolean Port_IsInitialized(void);

#endif /* ECUC_PORT_CFG_H */

/*==================[end of file]===========================================*/
/**
 * @page port_cfg_page Port Configuration
 * @brief This page documents the Port module configuration parameters.
 *
 * @section port_cfg_overview Overview
 * This configuration header defines all compile-time configuration parameters
 * for the Port AUTOSAR BSW module.
 *
 * @section port_cfg_usage Usage
 * Include this file in your Port module implementation to access
 * the configured parameters.
 *
 * @section port_cfg_dependencies Dependencies
 * - Std_Types.h: AUTOSAR standard type definitions
 * - Ecuc.h: ECU Configuration base definitions
 */
